2024-02-13 00:26:26,573 INFO    MainThread:10788 [internal.py:wandb_internal():87] W&B internal server running at pid: 10788, started at: 2024-02-13 00:26:26.572132
2024-02-13 00:26:26,576 INFO    WriterThread:10788 [datastore.py:open_for_write():77] open: D:\jichuang\CNN\mydata\wandb\run-20240213_002618-1j1aaaj0\run-1j1aaaj0.wandb
2024-02-13 00:26:26,576 DEBUG   HandlerThread:10788 [handler.py:handle_request():130] handle_request: check_version
2024-02-13 00:26:26,583 DEBUG   SenderThread:10788 [sender.py:send():238] send: header
2024-02-13 00:26:26,583 DEBUG   SenderThread:10788 [sender.py:send_request():252] send_request: check_version
2024-02-13 00:26:29,938 DEBUG   SenderThread:10788 [sender.py:send():238] send: run
2024-02-13 00:26:30,474 INFO    SenderThread:10788 [dir_watcher.py:__init__():169] watching files in: D:\jichuang\CNN\mydata\wandb\run-20240213_002618-1j1aaaj0\files
2024-02-13 00:26:30,474 INFO    SenderThread:10788 [sender.py:_start_run_threads():825] run started: 1j1aaaj0 with start time 1707755179
2024-02-13 00:26:30,475 DEBUG   SenderThread:10788 [sender.py:send():238] send: summary
2024-02-13 00:26:30,476 INFO    SenderThread:10788 [sender.py:_save_file():960] saving file wandb-summary.json with policy end
2024-02-13 00:26:30,481 DEBUG   HandlerThread:10788 [handler.py:handle_request():130] handle_request: run_start
2024-02-13 00:26:31,494 INFO    Thread-12 :10788 [dir_watcher.py:_on_file_created():217] file/dir created: D:\jichuang\CNN\mydata\wandb\run-20240213_002618-1j1aaaj0\files\wandb-summary.json
2024-02-13 00:26:35,657 INFO    Thread-12 :10788 [dir_watcher.py:_on_file_created():217] file/dir created: D:\jichuang\CNN\mydata\wandb\run-20240213_002618-1j1aaaj0\files\output.log
2024-02-13 00:26:37,675 INFO    Thread-12 :10788 [dir_watcher.py:_on_file_modified():230] file/dir modified: D:\jichuang\CNN\mydata\wandb\run-20240213_002618-1j1aaaj0\files\output.log
2024-02-13 00:26:39,753 INFO    Thread-12 :10788 [dir_watcher.py:_on_file_modified():230] file/dir modified: D:\jichuang\CNN\mydata\wandb\run-20240213_002618-1j1aaaj0\files\output.log
2024-02-13 00:26:41,451 DEBUG   HandlerThread:10788 [meta.py:__init__():40] meta init
2024-02-13 00:26:41,452 DEBUG   HandlerThread:10788 [meta.py:__init__():54] meta init done
2024-02-13 00:26:41,461 DEBUG   HandlerThread:10788 [meta.py:probe():214] probe
2024-02-13 00:26:41,578 DEBUG   HandlerThread:10788 [git.py:repo():33] git repository is invalid
2024-02-13 00:26:41,578 DEBUG   HandlerThread:10788 [meta.py:_save_pip():58] save pip
2024-02-13 00:26:41,582 DEBUG   HandlerThread:10788 [meta.py:_save_pip():72] save pip done
2024-02-13 00:26:41,583 DEBUG   HandlerThread:10788 [meta.py:_save_conda():79] save conda
2024-02-13 00:26:41,936 INFO    Thread-12 :10788 [dir_watcher.py:_on_file_created():217] file/dir created: D:\jichuang\CNN\mydata\wandb\run-20240213_002618-1j1aaaj0\files\conda-environment.yaml
2024-02-13 00:26:41,937 INFO    Thread-12 :10788 [dir_watcher.py:_on_file_created():217] file/dir created: D:\jichuang\CNN\mydata\wandb\run-20240213_002618-1j1aaaj0\files\requirements.txt
2024-02-13 00:26:43,955 INFO    Thread-12 :10788 [dir_watcher.py:_on_file_modified():230] file/dir modified: D:\jichuang\CNN\mydata\wandb\run-20240213_002618-1j1aaaj0\files\output.log
2024-02-13 00:26:50,032 INFO    Thread-12 :10788 [dir_watcher.py:_on_file_modified():230] file/dir modified: D:\jichuang\CNN\mydata\wandb\run-20240213_002618-1j1aaaj0\files\output.log
2024-02-13 00:26:58,126 DEBUG   HandlerThread:10788 [meta.py:_save_conda():89] save conda done
2024-02-13 00:26:58,126 DEBUG   HandlerThread:10788 [meta.py:probe():252] probe done
2024-02-13 00:26:58,146 DEBUG   HandlerThread:10788 [handler.py:handle_request():130] handle_request: stop_status
2024-02-13 00:26:58,146 DEBUG   SenderThread:10788 [sender.py:send_request():252] send_request: stop_status
2024-02-13 00:26:58,157 INFO    Thread-12 :10788 [dir_watcher.py:_on_file_created():217] file/dir created: D:\jichuang\CNN\mydata\wandb\run-20240213_002618-1j1aaaj0\files\wandb-metadata.json
2024-02-13 00:26:58,158 DEBUG   HandlerThread:10788 [handler.py:handle_request():130] handle_request: stop_status
2024-02-13 00:26:58,579 DEBUG   SenderThread:10788 [sender.py:send_request():252] send_request: stop_status
2024-02-13 00:26:59,034 DEBUG   SenderThread:10788 [sender.py:send():238] send: files
2024-02-13 00:26:59,035 INFO    SenderThread:10788 [sender.py:_save_file():960] saving file wandb-metadata.json with policy now
2024-02-13 00:26:59,548 ERROR   Thread-15 :10788 [internal_api.py:upload_file():1574] upload_file exception https://storage.googleapis.com/wandb-production.appspot.com/zhang-long/YOLOv8/1j1aaaj0/wandb-metadata.json?Expires=1707841619&GoogleAccessId=gorilla-files-url-signer-man%40wandb-production.iam.gserviceaccount.com&Signature=cZf8JvwvlyEan783%2FoIdBDuP%2FMRPKSJL8%2BJSgcHjEItD5k2%2FF7eKrUZ7lgys4kV2WsnuLKpQ5HnMsXpghu3%2FknwXChnrl1%2F0nA2B94diUHh2Uhfri%2BB5ySqP8gLS0rrstUyOyZStcDvpGbHoEOU39Bfe5R27RJ443lezMxVhCVVj9l2dEtnfHoyClDIBDQKJRW596k7G%2BOSXaA05gYm2S%2FFe9%2FXuFhKmtXBM9KC5LZy02%2FmmQolIV1%2F5KVe%2BbB7AuXJxrsuA%2FnvuWC4oj5wjPLIcueBkI5r6wmlTuRs4kmsq3UFS%2FEp1AzlXrAleSUkZeR41A8wIZML%2FdAYh4m8IwQ%3D%3D HTTPSConnectionPool(host='storage.googleapis.com', port=443): Max retries exceeded with url: /wandb-production.appspot.com/zhang-long/YOLOv8/1j1aaaj0/wandb-metadata.json?Expires=1707841619&GoogleAccessId=gorilla-files-url-signer-man%40wandb-production.iam.gserviceaccount.com&Signature=cZf8JvwvlyEan783%2FoIdBDuP%2FMRPKSJL8%2BJSgcHjEItD5k2%2FF7eKrUZ7lgys4kV2WsnuLKpQ5HnMsXpghu3%2FknwXChnrl1%2F0nA2B94diUHh2Uhfri%2BB5ySqP8gLS0rrstUyOyZStcDvpGbHoEOU39Bfe5R27RJ443lezMxVhCVVj9l2dEtnfHoyClDIBDQKJRW596k7G%2BOSXaA05gYm2S%2FFe9%2FXuFhKmtXBM9KC5LZy02%2FmmQolIV1%2F5KVe%2BbB7AuXJxrsuA%2FnvuWC4oj5wjPLIcueBkI5r6wmlTuRs4kmsq3UFS%2FEp1AzlXrAleSUkZeR41A8wIZML%2FdAYh4m8IwQ%3D%3D (Caused by NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x0000014CF549F2B0>: Failed to resolve 'storage.googleapis.com' ([Errno 11004] getaddrinfo failed)"))
2024-02-13 00:27:00,745 ERROR   Thread-15 :10788 [internal_api.py:upload_file():1574] upload_file exception https://storage.googleapis.com/wandb-production.appspot.com/zhang-long/YOLOv8/1j1aaaj0/wandb-metadata.json?Expires=1707841619&GoogleAccessId=gorilla-files-url-signer-man%40wandb-production.iam.gserviceaccount.com&Signature=cZf8JvwvlyEan783%2FoIdBDuP%2FMRPKSJL8%2BJSgcHjEItD5k2%2FF7eKrUZ7lgys4kV2WsnuLKpQ5HnMsXpghu3%2FknwXChnrl1%2F0nA2B94diUHh2Uhfri%2BB5ySqP8gLS0rrstUyOyZStcDvpGbHoEOU39Bfe5R27RJ443lezMxVhCVVj9l2dEtnfHoyClDIBDQKJRW596k7G%2BOSXaA05gYm2S%2FFe9%2FXuFhKmtXBM9KC5LZy02%2FmmQolIV1%2F5KVe%2BbB7AuXJxrsuA%2FnvuWC4oj5wjPLIcueBkI5r6wmlTuRs4kmsq3UFS%2FEp1AzlXrAleSUkZeR41A8wIZML%2FdAYh4m8IwQ%3D%3D HTTPSConnectionPool(host='storage.googleapis.com', port=443): Max retries exceeded with url: /wandb-production.appspot.com/zhang-long/YOLOv8/1j1aaaj0/wandb-metadata.json?Expires=1707841619&GoogleAccessId=gorilla-files-url-signer-man%40wandb-production.iam.gserviceaccount.com&Signature=cZf8JvwvlyEan783%2FoIdBDuP%2FMRPKSJL8%2BJSgcHjEItD5k2%2FF7eKrUZ7lgys4kV2WsnuLKpQ5HnMsXpghu3%2FknwXChnrl1%2F0nA2B94diUHh2Uhfri%2BB5ySqP8gLS0rrstUyOyZStcDvpGbHoEOU39Bfe5R27RJ443lezMxVhCVVj9l2dEtnfHoyClDIBDQKJRW596k7G%2BOSXaA05gYm2S%2FFe9%2FXuFhKmtXBM9KC5LZy02%2FmmQolIV1%2F5KVe%2BbB7AuXJxrsuA%2FnvuWC4oj5wjPLIcueBkI5r6wmlTuRs4kmsq3UFS%2FEp1AzlXrAleSUkZeR41A8wIZML%2FdAYh4m8IwQ%3D%3D (Caused by NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x0000014CF54BD460>: Failed to resolve 'storage.googleapis.com' ([Errno 11004] getaddrinfo failed)"))
2024-02-13 00:27:02,219 INFO    Thread-12 :10788 [dir_watcher.py:_on_file_modified():230] file/dir modified: D:\jichuang\CNN\mydata\wandb\run-20240213_002618-1j1aaaj0\files\output.log
2024-02-13 00:27:03,074 ERROR   Thread-15 :10788 [internal_api.py:upload_file():1574] upload_file exception https://storage.googleapis.com/wandb-production.appspot.com/zhang-long/YOLOv8/1j1aaaj0/wandb-metadata.json?Expires=1707841619&GoogleAccessId=gorilla-files-url-signer-man%40wandb-production.iam.gserviceaccount.com&Signature=cZf8JvwvlyEan783%2FoIdBDuP%2FMRPKSJL8%2BJSgcHjEItD5k2%2FF7eKrUZ7lgys4kV2WsnuLKpQ5HnMsXpghu3%2FknwXChnrl1%2F0nA2B94diUHh2Uhfri%2BB5ySqP8gLS0rrstUyOyZStcDvpGbHoEOU39Bfe5R27RJ443lezMxVhCVVj9l2dEtnfHoyClDIBDQKJRW596k7G%2BOSXaA05gYm2S%2FFe9%2FXuFhKmtXBM9KC5LZy02%2FmmQolIV1%2F5KVe%2BbB7AuXJxrsuA%2FnvuWC4oj5wjPLIcueBkI5r6wmlTuRs4kmsq3UFS%2FEp1AzlXrAleSUkZeR41A8wIZML%2FdAYh4m8IwQ%3D%3D HTTPSConnectionPool(host='storage.googleapis.com', port=443): Max retries exceeded with url: /wandb-production.appspot.com/zhang-long/YOLOv8/1j1aaaj0/wandb-metadata.json?Expires=1707841619&GoogleAccessId=gorilla-files-url-signer-man%40wandb-production.iam.gserviceaccount.com&Signature=cZf8JvwvlyEan783%2FoIdBDuP%2FMRPKSJL8%2BJSgcHjEItD5k2%2FF7eKrUZ7lgys4kV2WsnuLKpQ5HnMsXpghu3%2FknwXChnrl1%2F0nA2B94diUHh2Uhfri%2BB5ySqP8gLS0rrstUyOyZStcDvpGbHoEOU39Bfe5R27RJ443lezMxVhCVVj9l2dEtnfHoyClDIBDQKJRW596k7G%2BOSXaA05gYm2S%2FFe9%2FXuFhKmtXBM9KC5LZy02%2FmmQolIV1%2F5KVe%2BbB7AuXJxrsuA%2FnvuWC4oj5wjPLIcueBkI5r6wmlTuRs4kmsq3UFS%2FEp1AzlXrAleSUkZeR41A8wIZML%2FdAYh4m8IwQ%3D%3D (Caused by NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x0000014CF54BDDC0>: Failed to resolve 'storage.googleapis.com' ([Errno 11004] getaddrinfo failed)"))
2024-02-13 00:27:03,075 ERROR   Thread-15 :10788 [retry.py:__call__():126] Retry attempt failed:
Traceback (most recent call last):
  File "D:\anaconda\lib\site-packages\urllib3\connection.py", line 203, in _new_conn
    sock = connection.create_connection(
  File "D:\anaconda\lib\site-packages\urllib3\util\connection.py", line 60, in create_connection
    for res in socket.getaddrinfo(host, port, family, socket.SOCK_STREAM):
  File "D:\anaconda\lib\socket.py", line 918, in getaddrinfo
    for res in _socket.getaddrinfo(host, port, family, type, proto, flags):
socket.gaierror: [Errno 11004] getaddrinfo failed

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "D:\anaconda\lib\site-packages\urllib3\connectionpool.py", line 790, in urlopen
    response = self._make_request(
  File "D:\anaconda\lib\site-packages\urllib3\connectionpool.py", line 491, in _make_request
    raise new_e
  File "D:\anaconda\lib\site-packages\urllib3\connectionpool.py", line 467, in _make_request
    self._validate_conn(conn)
  File "D:\anaconda\lib\site-packages\urllib3\connectionpool.py", line 1096, in _validate_conn
    conn.connect()
  File "D:\anaconda\lib\site-packages\urllib3\connection.py", line 611, in connect
    self.sock = sock = self._new_conn()
  File "D:\anaconda\lib\site-packages\urllib3\connection.py", line 210, in _new_conn
    raise NameResolutionError(self.host, self, e) from e
urllib3.exceptions.NameResolutionError: <urllib3.connection.HTTPSConnection object at 0x0000014CF54BDDC0>: Failed to resolve 'storage.googleapis.com' ([Errno 11004] getaddrinfo failed)

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "D:\anaconda\lib\site-packages\requests\adapters.py", line 486, in send
    resp = conn.urlopen(
  File "D:\anaconda\lib\site-packages\urllib3\connectionpool.py", line 844, in urlopen
    retries = retries.increment(
  File "D:\anaconda\lib\site-packages\urllib3\util\retry.py", line 515, in increment
    raise MaxRetryError(_pool, url, reason) from reason  # type: ignore[arg-type]
urllib3.exceptions.MaxRetryError: HTTPSConnectionPool(host='storage.googleapis.com', port=443): Max retries exceeded with url: /wandb-production.appspot.com/zhang-long/YOLOv8/1j1aaaj0/wandb-metadata.json?Expires=1707841619&GoogleAccessId=gorilla-files-url-signer-man%40wandb-production.iam.gserviceaccount.com&Signature=cZf8JvwvlyEan783%2FoIdBDuP%2FMRPKSJL8%2BJSgcHjEItD5k2%2FF7eKrUZ7lgys4kV2WsnuLKpQ5HnMsXpghu3%2FknwXChnrl1%2F0nA2B94diUHh2Uhfri%2BB5ySqP8gLS0rrstUyOyZStcDvpGbHoEOU39Bfe5R27RJ443lezMxVhCVVj9l2dEtnfHoyClDIBDQKJRW596k7G%2BOSXaA05gYm2S%2FFe9%2FXuFhKmtXBM9KC5LZy02%2FmmQolIV1%2F5KVe%2BbB7AuXJxrsuA%2FnvuWC4oj5wjPLIcueBkI5r6wmlTuRs4kmsq3UFS%2FEp1AzlXrAleSUkZeR41A8wIZML%2FdAYh4m8IwQ%3D%3D (Caused by NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x0000014CF54BDDC0>: Failed to resolve 'storage.googleapis.com' ([Errno 11004] getaddrinfo failed)"))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "D:\anaconda\lib\site-packages\wandb\sdk\internal\internal_api.py", line 1571, in upload_file
    response = requests.put(url, data=progress, headers=extra_headers)
  File "D:\anaconda\lib\site-packages\requests\api.py", line 130, in put
    return request("put", url, data=data, **kwargs)
  File "D:\anaconda\lib\site-packages\requests\api.py", line 59, in request
    return session.request(method=method, url=url, **kwargs)
  File "D:\anaconda\lib\site-packages\requests\sessions.py", line 589, in request
    resp = self.send(prep, **send_kwargs)
  File "D:\anaconda\lib\site-packages\requests\sessions.py", line 703, in send
    r = adapter.send(request, **kwargs)
  File "D:\anaconda\lib\site-packages\requests\adapters.py", line 519, in send
    raise ConnectionError(e, request=request)
requests.exceptions.ConnectionError: HTTPSConnectionPool(host='storage.googleapis.com', port=443): Max retries exceeded with url: /wandb-production.appspot.com/zhang-long/YOLOv8/1j1aaaj0/wandb-metadata.json?Expires=1707841619&GoogleAccessId=gorilla-files-url-signer-man%40wandb-production.iam.gserviceaccount.com&Signature=cZf8JvwvlyEan783%2FoIdBDuP%2FMRPKSJL8%2BJSgcHjEItD5k2%2FF7eKrUZ7lgys4kV2WsnuLKpQ5HnMsXpghu3%2FknwXChnrl1%2F0nA2B94diUHh2Uhfri%2BB5ySqP8gLS0rrstUyOyZStcDvpGbHoEOU39Bfe5R27RJ443lezMxVhCVVj9l2dEtnfHoyClDIBDQKJRW596k7G%2BOSXaA05gYm2S%2FFe9%2FXuFhKmtXBM9KC5LZy02%2FmmQolIV1%2F5KVe%2BbB7AuXJxrsuA%2FnvuWC4oj5wjPLIcueBkI5r6wmlTuRs4kmsq3UFS%2FEp1AzlXrAleSUkZeR41A8wIZML%2FdAYh4m8IwQ%3D%3D (Caused by NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x0000014CF54BDDC0>: Failed to resolve 'storage.googleapis.com' ([Errno 11004] getaddrinfo failed)"))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "D:\anaconda\lib\site-packages\wandb\sdk\lib\retry.py", line 102, in __call__
    result = self._call_fn(*args, **kwargs)
  File "D:\anaconda\lib\site-packages\wandb\sdk\internal\internal_api.py", line 1583, in upload_file
    six.reraise(type(e), e, sys.exc_info()[2])
  File "D:\anaconda\lib\site-packages\six.py", line 718, in reraise
    raise value.with_traceback(tb)
  File "D:\anaconda\lib\site-packages\wandb\sdk\internal\internal_api.py", line 1571, in upload_file
    response = requests.put(url, data=progress, headers=extra_headers)
  File "D:\anaconda\lib\site-packages\requests\api.py", line 130, in put
    return request("put", url, data=data, **kwargs)
  File "D:\anaconda\lib\site-packages\requests\api.py", line 59, in request
    return session.request(method=method, url=url, **kwargs)
  File "D:\anaconda\lib\site-packages\requests\sessions.py", line 589, in request
    resp = self.send(prep, **send_kwargs)
  File "D:\anaconda\lib\site-packages\requests\sessions.py", line 703, in send
    r = adapter.send(request, **kwargs)
  File "D:\anaconda\lib\site-packages\requests\adapters.py", line 519, in send
    raise ConnectionError(e, request=request)
wandb.sdk.lib.retry.TransientError: None
2024-02-13 00:27:04,274 INFO    Thread-12 :10788 [dir_watcher.py:_on_file_modified():230] file/dir modified: D:\jichuang\CNN\mydata\wandb\run-20240213_002618-1j1aaaj0\files\output.log
2024-02-13 00:27:07,891 ERROR   Thread-15 :10788 [internal_api.py:upload_file():1574] upload_file exception https://storage.googleapis.com/wandb-production.appspot.com/zhang-long/YOLOv8/1j1aaaj0/wandb-metadata.json?Expires=1707841619&GoogleAccessId=gorilla-files-url-signer-man%40wandb-production.iam.gserviceaccount.com&Signature=cZf8JvwvlyEan783%2FoIdBDuP%2FMRPKSJL8%2BJSgcHjEItD5k2%2FF7eKrUZ7lgys4kV2WsnuLKpQ5HnMsXpghu3%2FknwXChnrl1%2F0nA2B94diUHh2Uhfri%2BB5ySqP8gLS0rrstUyOyZStcDvpGbHoEOU39Bfe5R27RJ443lezMxVhCVVj9l2dEtnfHoyClDIBDQKJRW596k7G%2BOSXaA05gYm2S%2FFe9%2FXuFhKmtXBM9KC5LZy02%2FmmQolIV1%2F5KVe%2BbB7AuXJxrsuA%2FnvuWC4oj5wjPLIcueBkI5r6wmlTuRs4kmsq3UFS%2FEp1AzlXrAleSUkZeR41A8wIZML%2FdAYh4m8IwQ%3D%3D HTTPSConnectionPool(host='storage.googleapis.com', port=443): Max retries exceeded with url: /wandb-production.appspot.com/zhang-long/YOLOv8/1j1aaaj0/wandb-metadata.json?Expires=1707841619&GoogleAccessId=gorilla-files-url-signer-man%40wandb-production.iam.gserviceaccount.com&Signature=cZf8JvwvlyEan783%2FoIdBDuP%2FMRPKSJL8%2BJSgcHjEItD5k2%2FF7eKrUZ7lgys4kV2WsnuLKpQ5HnMsXpghu3%2FknwXChnrl1%2F0nA2B94diUHh2Uhfri%2BB5ySqP8gLS0rrstUyOyZStcDvpGbHoEOU39Bfe5R27RJ443lezMxVhCVVj9l2dEtnfHoyClDIBDQKJRW596k7G%2BOSXaA05gYm2S%2FFe9%2FXuFhKmtXBM9KC5LZy02%2FmmQolIV1%2F5KVe%2BbB7AuXJxrsuA%2FnvuWC4oj5wjPLIcueBkI5r6wmlTuRs4kmsq3UFS%2FEp1AzlXrAleSUkZeR41A8wIZML%2FdAYh4m8IwQ%3D%3D (Caused by NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x0000014CF54BD6D0>: Failed to resolve 'storage.googleapis.com' ([Errno 11004] getaddrinfo failed)"))
2024-02-13 00:27:13,887 DEBUG   SenderThread:10788 [sender.py:send():238] send: stats
2024-02-13 00:27:14,042 DEBUG   HandlerThread:10788 [handler.py:handle_request():130] handle_request: stop_status
2024-02-13 00:27:14,042 DEBUG   SenderThread:10788 [sender.py:send_request():252] send_request: stop_status
2024-02-13 00:27:16,216 ERROR   Thread-15 :10788 [internal_api.py:upload_file():1574] upload_file exception https://storage.googleapis.com/wandb-production.appspot.com/zhang-long/YOLOv8/1j1aaaj0/wandb-metadata.json?Expires=1707841619&GoogleAccessId=gorilla-files-url-signer-man%40wandb-production.iam.gserviceaccount.com&Signature=cZf8JvwvlyEan783%2FoIdBDuP%2FMRPKSJL8%2BJSgcHjEItD5k2%2FF7eKrUZ7lgys4kV2WsnuLKpQ5HnMsXpghu3%2FknwXChnrl1%2F0nA2B94diUHh2Uhfri%2BB5ySqP8gLS0rrstUyOyZStcDvpGbHoEOU39Bfe5R27RJ443lezMxVhCVVj9l2dEtnfHoyClDIBDQKJRW596k7G%2BOSXaA05gYm2S%2FFe9%2FXuFhKmtXBM9KC5LZy02%2FmmQolIV1%2F5KVe%2BbB7AuXJxrsuA%2FnvuWC4oj5wjPLIcueBkI5r6wmlTuRs4kmsq3UFS%2FEp1AzlXrAleSUkZeR41A8wIZML%2FdAYh4m8IwQ%3D%3D HTTPSConnectionPool(host='storage.googleapis.com', port=443): Max retries exceeded with url: /wandb-production.appspot.com/zhang-long/YOLOv8/1j1aaaj0/wandb-metadata.json?Expires=1707841619&GoogleAccessId=gorilla-files-url-signer-man%40wandb-production.iam.gserviceaccount.com&Signature=cZf8JvwvlyEan783%2FoIdBDuP%2FMRPKSJL8%2BJSgcHjEItD5k2%2FF7eKrUZ7lgys4kV2WsnuLKpQ5HnMsXpghu3%2FknwXChnrl1%2F0nA2B94diUHh2Uhfri%2BB5ySqP8gLS0rrstUyOyZStcDvpGbHoEOU39Bfe5R27RJ443lezMxVhCVVj9l2dEtnfHoyClDIBDQKJRW596k7G%2BOSXaA05gYm2S%2FFe9%2FXuFhKmtXBM9KC5LZy02%2FmmQolIV1%2F5KVe%2BbB7AuXJxrsuA%2FnvuWC4oj5wjPLIcueBkI5r6wmlTuRs4kmsq3UFS%2FEp1AzlXrAleSUkZeR41A8wIZML%2FdAYh4m8IwQ%3D%3D (Caused by NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x0000014CF549F7F0>: Failed to resolve 'storage.googleapis.com' ([Errno 11004] getaddrinfo failed)"))
2024-02-13 00:27:29,474 DEBUG   HandlerThread:10788 [handler.py:handle_request():130] handle_request: stop_status
2024-02-13 00:27:29,474 DEBUG   SenderThread:10788 [sender.py:send_request():252] send_request: stop_status
2024-02-13 00:27:35,757 ERROR   Thread-15 :10788 [internal_api.py:upload_file():1574] upload_file exception https://storage.googleapis.com/wandb-production.appspot.com/zhang-long/YOLOv8/1j1aaaj0/wandb-metadata.json?Expires=1707841619&GoogleAccessId=gorilla-files-url-signer-man%40wandb-production.iam.gserviceaccount.com&Signature=cZf8JvwvlyEan783%2FoIdBDuP%2FMRPKSJL8%2BJSgcHjEItD5k2%2FF7eKrUZ7lgys4kV2WsnuLKpQ5HnMsXpghu3%2FknwXChnrl1%2F0nA2B94diUHh2Uhfri%2BB5ySqP8gLS0rrstUyOyZStcDvpGbHoEOU39Bfe5R27RJ443lezMxVhCVVj9l2dEtnfHoyClDIBDQKJRW596k7G%2BOSXaA05gYm2S%2FFe9%2FXuFhKmtXBM9KC5LZy02%2FmmQolIV1%2F5KVe%2BbB7AuXJxrsuA%2FnvuWC4oj5wjPLIcueBkI5r6wmlTuRs4kmsq3UFS%2FEp1AzlXrAleSUkZeR41A8wIZML%2FdAYh4m8IwQ%3D%3D HTTPSConnectionPool(host='storage.googleapis.com', port=443): Max retries exceeded with url: /wandb-production.appspot.com/zhang-long/YOLOv8/1j1aaaj0/wandb-metadata.json?Expires=1707841619&GoogleAccessId=gorilla-files-url-signer-man%40wandb-production.iam.gserviceaccount.com&Signature=cZf8JvwvlyEan783%2FoIdBDuP%2FMRPKSJL8%2BJSgcHjEItD5k2%2FF7eKrUZ7lgys4kV2WsnuLKpQ5HnMsXpghu3%2FknwXChnrl1%2F0nA2B94diUHh2Uhfri%2BB5ySqP8gLS0rrstUyOyZStcDvpGbHoEOU39Bfe5R27RJ443lezMxVhCVVj9l2dEtnfHoyClDIBDQKJRW596k7G%2BOSXaA05gYm2S%2FFe9%2FXuFhKmtXBM9KC5LZy02%2FmmQolIV1%2F5KVe%2BbB7AuXJxrsuA%2FnvuWC4oj5wjPLIcueBkI5r6wmlTuRs4kmsq3UFS%2FEp1AzlXrAleSUkZeR41A8wIZML%2FdAYh4m8IwQ%3D%3D (Caused by NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x0000014CF5588910>: Failed to resolve 'storage.googleapis.com' ([Errno 11004] getaddrinfo failed)"))
2024-02-13 00:27:44,962 DEBUG   HandlerThread:10788 [handler.py:handle_request():130] handle_request: stop_status
2024-02-13 00:27:44,972 DEBUG   SenderThread:10788 [sender.py:send_request():252] send_request: stop_status
2024-02-13 00:27:47,187 INFO    Thread-12 :10788 [dir_watcher.py:_on_file_modified():230] file/dir modified: D:\jichuang\CNN\mydata\wandb\run-20240213_002618-1j1aaaj0\files\output.log
2024-02-13 00:27:50,239 DEBUG   SenderThread:10788 [sender.py:send():238] send: stats
2024-02-13 00:28:00,447 DEBUG   HandlerThread:10788 [handler.py:handle_request():130] handle_request: stop_status
2024-02-13 00:28:00,448 DEBUG   SenderThread:10788 [sender.py:send_request():252] send_request: stop_status
2024-02-13 00:28:08,353 ERROR   Thread-15 :10788 [internal_api.py:upload_file():1574] upload_file exception https://storage.googleapis.com/wandb-production.appspot.com/zhang-long/YOLOv8/1j1aaaj0/wandb-metadata.json?Expires=1707841619&GoogleAccessId=gorilla-files-url-signer-man%40wandb-production.iam.gserviceaccount.com&Signature=cZf8JvwvlyEan783%2FoIdBDuP%2FMRPKSJL8%2BJSgcHjEItD5k2%2FF7eKrUZ7lgys4kV2WsnuLKpQ5HnMsXpghu3%2FknwXChnrl1%2F0nA2B94diUHh2Uhfri%2BB5ySqP8gLS0rrstUyOyZStcDvpGbHoEOU39Bfe5R27RJ443lezMxVhCVVj9l2dEtnfHoyClDIBDQKJRW596k7G%2BOSXaA05gYm2S%2FFe9%2FXuFhKmtXBM9KC5LZy02%2FmmQolIV1%2F5KVe%2BbB7AuXJxrsuA%2FnvuWC4oj5wjPLIcueBkI5r6wmlTuRs4kmsq3UFS%2FEp1AzlXrAleSUkZeR41A8wIZML%2FdAYh4m8IwQ%3D%3D HTTPSConnectionPool(host='storage.googleapis.com', port=443): Max retries exceeded with url: /wandb-production.appspot.com/zhang-long/YOLOv8/1j1aaaj0/wandb-metadata.json?Expires=1707841619&GoogleAccessId=gorilla-files-url-signer-man%40wandb-production.iam.gserviceaccount.com&Signature=cZf8JvwvlyEan783%2FoIdBDuP%2FMRPKSJL8%2BJSgcHjEItD5k2%2FF7eKrUZ7lgys4kV2WsnuLKpQ5HnMsXpghu3%2FknwXChnrl1%2F0nA2B94diUHh2Uhfri%2BB5ySqP8gLS0rrstUyOyZStcDvpGbHoEOU39Bfe5R27RJ443lezMxVhCVVj9l2dEtnfHoyClDIBDQKJRW596k7G%2BOSXaA05gYm2S%2FFe9%2FXuFhKmtXBM9KC5LZy02%2FmmQolIV1%2F5KVe%2BbB7AuXJxrsuA%2FnvuWC4oj5wjPLIcueBkI5r6wmlTuRs4kmsq3UFS%2FEp1AzlXrAleSUkZeR41A8wIZML%2FdAYh4m8IwQ%3D%3D (Caused by NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x0000014CF5588BE0>: Failed to resolve 'storage.googleapis.com' ([Errno 11004] getaddrinfo failed)"))
2024-02-13 00:28:15,933 DEBUG   HandlerThread:10788 [handler.py:handle_request():130] handle_request: stop_status
2024-02-13 00:28:15,934 DEBUG   SenderThread:10788 [sender.py:send_request():252] send_request: stop_status
2024-02-13 00:28:24,951 INFO    Thread-12 :10788 [dir_watcher.py:_on_file_modified():230] file/dir modified: D:\jichuang\CNN\mydata\wandb\run-20240213_002618-1j1aaaj0\files\output.log
2024-02-13 00:28:26,031 DEBUG   SenderThread:10788 [sender.py:send():238] send: stats
2024-02-13 00:28:31,426 DEBUG   HandlerThread:10788 [handler.py:handle_request():130] handle_request: stop_status
2024-02-13 00:28:31,427 DEBUG   SenderThread:10788 [sender.py:send_request():252] send_request: stop_status
2024-02-13 00:28:46,890 DEBUG   HandlerThread:10788 [handler.py:handle_request():130] handle_request: stop_status
2024-02-13 00:28:46,891 DEBUG   SenderThread:10788 [sender.py:send_request():252] send_request: stop_status
2024-02-13 00:29:01,568 DEBUG   SenderThread:10788 [sender.py:send():238] send: stats
2024-02-13 00:29:01,680 INFO    Thread-12 :10788 [dir_watcher.py:_on_file_modified():230] file/dir modified: D:\jichuang\CNN\mydata\wandb\run-20240213_002618-1j1aaaj0\files\output.log
2024-02-13 00:29:02,409 DEBUG   HandlerThread:10788 [handler.py:handle_request():130] handle_request: stop_status
2024-02-13 00:29:02,410 DEBUG   SenderThread:10788 [sender.py:send_request():252] send_request: stop_status
2024-02-13 00:29:20,452 DEBUG   HandlerThread:10788 [handler.py:handle_request():130] handle_request: stop_status
2024-02-13 00:29:20,453 DEBUG   SenderThread:10788 [sender.py:send_request():252] send_request: stop_status
2024-02-13 00:29:22,810 ERROR   Thread-15 :10788 [internal_api.py:upload_file():1574] upload_file exception https://storage.googleapis.com/wandb-production.appspot.com/zhang-long/YOLOv8/1j1aaaj0/wandb-metadata.json?Expires=1707841619&GoogleAccessId=gorilla-files-url-signer-man%40wandb-production.iam.gserviceaccount.com&Signature=cZf8JvwvlyEan783%2FoIdBDuP%2FMRPKSJL8%2BJSgcHjEItD5k2%2FF7eKrUZ7lgys4kV2WsnuLKpQ5HnMsXpghu3%2FknwXChnrl1%2F0nA2B94diUHh2Uhfri%2BB5ySqP8gLS0rrstUyOyZStcDvpGbHoEOU39Bfe5R27RJ443lezMxVhCVVj9l2dEtnfHoyClDIBDQKJRW596k7G%2BOSXaA05gYm2S%2FFe9%2FXuFhKmtXBM9KC5LZy02%2FmmQolIV1%2F5KVe%2BbB7AuXJxrsuA%2FnvuWC4oj5wjPLIcueBkI5r6wmlTuRs4kmsq3UFS%2FEp1AzlXrAleSUkZeR41A8wIZML%2FdAYh4m8IwQ%3D%3D HTTPSConnectionPool(host='storage.googleapis.com', port=443): Max retries exceeded with url: /wandb-production.appspot.com/zhang-long/YOLOv8/1j1aaaj0/wandb-metadata.json?Expires=1707841619&GoogleAccessId=gorilla-files-url-signer-man%40wandb-production.iam.gserviceaccount.com&Signature=cZf8JvwvlyEan783%2FoIdBDuP%2FMRPKSJL8%2BJSgcHjEItD5k2%2FF7eKrUZ7lgys4kV2WsnuLKpQ5HnMsXpghu3%2FknwXChnrl1%2F0nA2B94diUHh2Uhfri%2BB5ySqP8gLS0rrstUyOyZStcDvpGbHoEOU39Bfe5R27RJ443lezMxVhCVVj9l2dEtnfHoyClDIBDQKJRW596k7G%2BOSXaA05gYm2S%2FFe9%2FXuFhKmtXBM9KC5LZy02%2FmmQolIV1%2F5KVe%2BbB7AuXJxrsuA%2FnvuWC4oj5wjPLIcueBkI5r6wmlTuRs4kmsq3UFS%2FEp1AzlXrAleSUkZeR41A8wIZML%2FdAYh4m8IwQ%3D%3D (Caused by NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x0000014CF54BD400>: Failed to resolve 'storage.googleapis.com' ([Errno 11004] getaddrinfo failed)"))
2024-02-13 00:29:35,968 DEBUG   HandlerThread:10788 [handler.py:handle_request():130] handle_request: stop_status
2024-02-13 00:29:35,968 DEBUG   SenderThread:10788 [sender.py:send_request():252] send_request: stop_status
2024-02-13 00:29:36,990 DEBUG   SenderThread:10788 [sender.py:send():238] send: stats
2024-02-13 00:29:38,313 INFO    Thread-12 :10788 [dir_watcher.py:_on_file_modified():230] file/dir modified: D:\jichuang\CNN\mydata\wandb\run-20240213_002618-1j1aaaj0\files\output.log
2024-02-13 00:29:51,449 DEBUG   HandlerThread:10788 [handler.py:handle_request():130] handle_request: stop_status
2024-02-13 00:29:51,450 DEBUG   SenderThread:10788 [sender.py:send_request():252] send_request: stop_status
2024-02-13 00:30:06,913 DEBUG   HandlerThread:10788 [handler.py:handle_request():130] handle_request: stop_status
2024-02-13 00:30:06,913 DEBUG   SenderThread:10788 [sender.py:send_request():252] send_request: stop_status
2024-02-13 00:30:11,877 INFO    Thread-12 :10788 [dir_watcher.py:_on_file_modified():230] file/dir modified: D:\jichuang\CNN\mydata\wandb\run-20240213_002618-1j1aaaj0\files\output.log
2024-02-13 00:30:12,187 DEBUG   SenderThread:10788 [sender.py:send():238] send: stats
2024-02-13 00:30:22,384 DEBUG   HandlerThread:10788 [handler.py:handle_request():130] handle_request: stop_status
2024-02-13 00:30:22,385 DEBUG   SenderThread:10788 [sender.py:send_request():252] send_request: stop_status
2024-02-13 00:30:37,947 DEBUG   HandlerThread:10788 [handler.py:handle_request():130] handle_request: stop_status
2024-02-13 00:30:37,947 DEBUG   SenderThread:10788 [sender.py:send_request():252] send_request: stop_status
2024-02-13 00:30:48,377 DEBUG   SenderThread:10788 [sender.py:send():238] send: stats
2024-02-13 00:30:53,424 DEBUG   HandlerThread:10788 [handler.py:handle_request():130] handle_request: stop_status
2024-02-13 00:30:53,425 DEBUG   SenderThread:10788 [sender.py:send_request():252] send_request: stop_status
2024-02-13 00:30:56,813 INFO    Thread-12 :10788 [dir_watcher.py:_on_file_modified():230] file/dir modified: D:\jichuang\CNN\mydata\wandb\run-20240213_002618-1j1aaaj0\files\output.log
2024-02-13 00:31:08,920 DEBUG   HandlerThread:10788 [handler.py:handle_request():130] handle_request: stop_status
2024-02-13 00:31:08,921 DEBUG   SenderThread:10788 [sender.py:send_request():252] send_request: stop_status
2024-02-13 00:31:24,351 DEBUG   HandlerThread:10788 [handler.py:handle_request():130] handle_request: stop_status
2024-02-13 00:31:24,415 DEBUG   SenderThread:10788 [sender.py:send_request():252] send_request: stop_status
2024-02-13 00:31:24,984 DEBUG   SenderThread:10788 [sender.py:send():238] send: stats
2024-02-13 00:31:36,808 INFO    Thread-12 :10788 [dir_watcher.py:_on_file_modified():230] file/dir modified: D:\jichuang\CNN\mydata\wandb\run-20240213_002618-1j1aaaj0\files\output.log
2024-02-13 00:31:39,989 DEBUG   HandlerThread:10788 [handler.py:handle_request():130] handle_request: stop_status
2024-02-13 00:31:39,990 DEBUG   SenderThread:10788 [sender.py:send_request():252] send_request: stop_status
2024-02-13 00:31:55,430 DEBUG   HandlerThread:10788 [handler.py:handle_request():130] handle_request: stop_status
2024-02-13 00:31:55,430 DEBUG   SenderThread:10788 [sender.py:send_request():252] send_request: stop_status
2024-02-13 00:31:59,813 DEBUG   SenderThread:10788 [sender.py:send():238] send: stats
2024-02-13 00:32:00,059 ERROR   Thread-15 :10788 [internal_api.py:upload_file():1574] upload_file exception https://storage.googleapis.com/wandb-production.appspot.com/zhang-long/YOLOv8/1j1aaaj0/wandb-metadata.json?Expires=1707841619&GoogleAccessId=gorilla-files-url-signer-man%40wandb-production.iam.gserviceaccount.com&Signature=cZf8JvwvlyEan783%2FoIdBDuP%2FMRPKSJL8%2BJSgcHjEItD5k2%2FF7eKrUZ7lgys4kV2WsnuLKpQ5HnMsXpghu3%2FknwXChnrl1%2F0nA2B94diUHh2Uhfri%2BB5ySqP8gLS0rrstUyOyZStcDvpGbHoEOU39Bfe5R27RJ443lezMxVhCVVj9l2dEtnfHoyClDIBDQKJRW596k7G%2BOSXaA05gYm2S%2FFe9%2FXuFhKmtXBM9KC5LZy02%2FmmQolIV1%2F5KVe%2BbB7AuXJxrsuA%2FnvuWC4oj5wjPLIcueBkI5r6wmlTuRs4kmsq3UFS%2FEp1AzlXrAleSUkZeR41A8wIZML%2FdAYh4m8IwQ%3D%3D HTTPSConnectionPool(host='storage.googleapis.com', port=443): Max retries exceeded with url: /wandb-production.appspot.com/zhang-long/YOLOv8/1j1aaaj0/wandb-metadata.json?Expires=1707841619&GoogleAccessId=gorilla-files-url-signer-man%40wandb-production.iam.gserviceaccount.com&Signature=cZf8JvwvlyEan783%2FoIdBDuP%2FMRPKSJL8%2BJSgcHjEItD5k2%2FF7eKrUZ7lgys4kV2WsnuLKpQ5HnMsXpghu3%2FknwXChnrl1%2F0nA2B94diUHh2Uhfri%2BB5ySqP8gLS0rrstUyOyZStcDvpGbHoEOU39Bfe5R27RJ443lezMxVhCVVj9l2dEtnfHoyClDIBDQKJRW596k7G%2BOSXaA05gYm2S%2FFe9%2FXuFhKmtXBM9KC5LZy02%2FmmQolIV1%2F5KVe%2BbB7AuXJxrsuA%2FnvuWC4oj5wjPLIcueBkI5r6wmlTuRs4kmsq3UFS%2FEp1AzlXrAleSUkZeR41A8wIZML%2FdAYh4m8IwQ%3D%3D (Caused by NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x0000014CF558B1C0>: Failed to resolve 'storage.googleapis.com' ([Errno 11004] getaddrinfo failed)"))
2024-02-13 00:32:10,931 DEBUG   HandlerThread:10788 [handler.py:handle_request():130] handle_request: stop_status
2024-02-13 00:32:10,931 DEBUG   SenderThread:10788 [sender.py:send_request():252] send_request: stop_status
2024-02-13 00:32:11,451 INFO    Thread-12 :10788 [dir_watcher.py:_on_file_modified():230] file/dir modified: D:\jichuang\CNN\mydata\wandb\run-20240213_002618-1j1aaaj0\files\output.log
2024-02-13 00:32:26,451 DEBUG   HandlerThread:10788 [handler.py:handle_request():130] handle_request: stop_status
2024-02-13 00:32:26,452 DEBUG   SenderThread:10788 [sender.py:send_request():252] send_request: stop_status
2024-02-13 00:32:35,541 DEBUG   SenderThread:10788 [sender.py:send():238] send: stats
2024-02-13 00:32:41,936 DEBUG   HandlerThread:10788 [handler.py:handle_request():130] handle_request: stop_status
2024-02-13 00:32:41,937 DEBUG   SenderThread:10788 [sender.py:send_request():252] send_request: stop_status
2024-02-13 00:32:50,172 INFO    Thread-12 :10788 [dir_watcher.py:_on_file_modified():230] file/dir modified: D:\jichuang\CNN\mydata\wandb\run-20240213_002618-1j1aaaj0\files\output.log
2024-02-13 00:32:57,499 DEBUG   HandlerThread:10788 [handler.py:handle_request():130] handle_request: stop_status
2024-02-13 00:32:57,500 DEBUG   SenderThread:10788 [sender.py:send_request():252] send_request: stop_status
2024-02-13 00:33:10,890 DEBUG   SenderThread:10788 [sender.py:send():238] send: stats
2024-02-13 00:33:12,955 DEBUG   HandlerThread:10788 [handler.py:handle_request():130] handle_request: stop_status
2024-02-13 00:33:12,955 DEBUG   SenderThread:10788 [sender.py:send_request():252] send_request: stop_status
2024-02-13 00:33:23,845 INFO    Thread-12 :10788 [dir_watcher.py:_on_file_modified():230] file/dir modified: D:\jichuang\CNN\mydata\wandb\run-20240213_002618-1j1aaaj0\files\output.log
2024-02-13 00:33:28,404 DEBUG   HandlerThread:10788 [handler.py:handle_request():130] handle_request: stop_status
2024-02-13 00:33:28,404 DEBUG   SenderThread:10788 [sender.py:send_request():252] send_request: stop_status
2024-02-13 00:33:43,901 DEBUG   HandlerThread:10788 [handler.py:handle_request():130] handle_request: stop_status
2024-02-13 00:33:43,902 DEBUG   SenderThread:10788 [sender.py:send_request():252] send_request: stop_status
2024-02-13 00:33:46,542 DEBUG   SenderThread:10788 [sender.py:send():238] send: stats
2024-02-13 00:33:59,333 DEBUG   HandlerThread:10788 [handler.py:handle_request():130] handle_request: stop_status
2024-02-13 00:33:59,333 DEBUG   SenderThread:10788 [sender.py:send_request():252] send_request: stop_status
2024-02-13 00:34:00,546 INFO    Thread-12 :10788 [dir_watcher.py:_on_file_modified():230] file/dir modified: D:\jichuang\CNN\mydata\wandb\run-20240213_002618-1j1aaaj0\files\output.log
2024-02-13 00:34:14,809 DEBUG   HandlerThread:10788 [handler.py:handle_request():130] handle_request: stop_status
2024-02-13 00:34:14,810 DEBUG   SenderThread:10788 [sender.py:send_request():252] send_request: stop_status
2024-02-13 00:34:22,148 DEBUG   SenderThread:10788 [sender.py:send():238] send: stats
2024-02-13 00:34:30,370 DEBUG   HandlerThread:10788 [handler.py:handle_request():130] handle_request: stop_status
2024-02-13 00:34:30,370 DEBUG   SenderThread:10788 [sender.py:send_request():252] send_request: stop_status
2024-02-13 00:34:38,335 INFO    Thread-12 :10788 [dir_watcher.py:_on_file_modified():230] file/dir modified: D:\jichuang\CNN\mydata\wandb\run-20240213_002618-1j1aaaj0\files\output.log
2024-02-13 00:34:45,864 DEBUG   HandlerThread:10788 [handler.py:handle_request():130] handle_request: stop_status
2024-02-13 00:34:45,864 DEBUG   SenderThread:10788 [sender.py:send_request():252] send_request: stop_status
2024-02-13 00:34:57,536 DEBUG   SenderThread:10788 [sender.py:send():238] send: stats
2024-02-13 00:35:01,342 DEBUG   HandlerThread:10788 [handler.py:handle_request():130] handle_request: stop_status
2024-02-13 00:35:01,342 DEBUG   SenderThread:10788 [sender.py:send_request():252] send_request: stop_status
2024-02-13 00:35:10,953 INFO    Thread-12 :10788 [dir_watcher.py:_on_file_modified():230] file/dir modified: D:\jichuang\CNN\mydata\wandb\run-20240213_002618-1j1aaaj0\files\output.log
2024-02-13 00:35:16,794 DEBUG   HandlerThread:10788 [handler.py:handle_request():130] handle_request: stop_status
2024-02-13 00:35:16,794 DEBUG   SenderThread:10788 [sender.py:send_request():252] send_request: stop_status
2024-02-13 00:35:32,240 DEBUG   HandlerThread:10788 [handler.py:handle_request():130] handle_request: stop_status
2024-02-13 00:35:32,240 DEBUG   SenderThread:10788 [sender.py:send_request():252] send_request: stop_status
2024-02-13 00:35:33,380 DEBUG   SenderThread:10788 [sender.py:send():238] send: stats
2024-02-13 00:35:47,766 DEBUG   HandlerThread:10788 [handler.py:handle_request():130] handle_request: stop_status
2024-02-13 00:35:47,767 DEBUG   SenderThread:10788 [sender.py:send_request():252] send_request: stop_status
2024-02-13 00:35:50,779 INFO    Thread-12 :10788 [dir_watcher.py:_on_file_modified():230] file/dir modified: D:\jichuang\CNN\mydata\wandb\run-20240213_002618-1j1aaaj0\files\output.log
2024-02-13 00:36:03,247 DEBUG   HandlerThread:10788 [handler.py:handle_request():130] handle_request: stop_status
2024-02-13 00:36:03,248 DEBUG   SenderThread:10788 [sender.py:send_request():252] send_request: stop_status
2024-02-13 00:36:09,151 DEBUG   SenderThread:10788 [sender.py:send():238] send: stats
2024-02-13 00:36:18,674 DEBUG   HandlerThread:10788 [handler.py:handle_request():130] handle_request: stop_status
2024-02-13 00:36:18,674 DEBUG   SenderThread:10788 [sender.py:send_request():252] send_request: stop_status
2024-02-13 00:36:31,580 INFO    Thread-12 :10788 [dir_watcher.py:_on_file_modified():230] file/dir modified: D:\jichuang\CNN\mydata\wandb\run-20240213_002618-1j1aaaj0\files\output.log
2024-02-13 00:36:34,214 DEBUG   HandlerThread:10788 [handler.py:handle_request():130] handle_request: stop_status
2024-02-13 00:36:34,215 DEBUG   SenderThread:10788 [sender.py:send_request():252] send_request: stop_status
2024-02-13 00:36:43,777 ERROR   Thread-15 :10788 [internal_api.py:upload_file():1574] upload_file exception https://storage.googleapis.com/wandb-production.appspot.com/zhang-long/YOLOv8/1j1aaaj0/wandb-metadata.json?Expires=1707841619&GoogleAccessId=gorilla-files-url-signer-man%40wandb-production.iam.gserviceaccount.com&Signature=cZf8JvwvlyEan783%2FoIdBDuP%2FMRPKSJL8%2BJSgcHjEItD5k2%2FF7eKrUZ7lgys4kV2WsnuLKpQ5HnMsXpghu3%2FknwXChnrl1%2F0nA2B94diUHh2Uhfri%2BB5ySqP8gLS0rrstUyOyZStcDvpGbHoEOU39Bfe5R27RJ443lezMxVhCVVj9l2dEtnfHoyClDIBDQKJRW596k7G%2BOSXaA05gYm2S%2FFe9%2FXuFhKmtXBM9KC5LZy02%2FmmQolIV1%2F5KVe%2BbB7AuXJxrsuA%2FnvuWC4oj5wjPLIcueBkI5r6wmlTuRs4kmsq3UFS%2FEp1AzlXrAleSUkZeR41A8wIZML%2FdAYh4m8IwQ%3D%3D HTTPSConnectionPool(host='storage.googleapis.com', port=443): Max retries exceeded with url: /wandb-production.appspot.com/zhang-long/YOLOv8/1j1aaaj0/wandb-metadata.json?Expires=1707841619&GoogleAccessId=gorilla-files-url-signer-man%40wandb-production.iam.gserviceaccount.com&Signature=cZf8JvwvlyEan783%2FoIdBDuP%2FMRPKSJL8%2BJSgcHjEItD5k2%2FF7eKrUZ7lgys4kV2WsnuLKpQ5HnMsXpghu3%2FknwXChnrl1%2F0nA2B94diUHh2Uhfri%2BB5ySqP8gLS0rrstUyOyZStcDvpGbHoEOU39Bfe5R27RJ443lezMxVhCVVj9l2dEtnfHoyClDIBDQKJRW596k7G%2BOSXaA05gYm2S%2FFe9%2FXuFhKmtXBM9KC5LZy02%2FmmQolIV1%2F5KVe%2BbB7AuXJxrsuA%2FnvuWC4oj5wjPLIcueBkI5r6wmlTuRs4kmsq3UFS%2FEp1AzlXrAleSUkZeR41A8wIZML%2FdAYh4m8IwQ%3D%3D (Caused by NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x0000014CF549FA00>: Failed to resolve 'storage.googleapis.com' ([Errno 11004] getaddrinfo failed)"))
2024-02-13 00:36:44,775 DEBUG   SenderThread:10788 [sender.py:send():238] send: stats
2024-02-13 00:36:49,855 DEBUG   HandlerThread:10788 [handler.py:handle_request():130] handle_request: stop_status
2024-02-13 00:36:49,855 DEBUG   SenderThread:10788 [sender.py:send_request():252] send_request: stop_status
2024-02-13 00:37:05,483 DEBUG   HandlerThread:10788 [handler.py:handle_request():130] handle_request: stop_status
2024-02-13 00:37:05,483 DEBUG   SenderThread:10788 [sender.py:send_request():252] send_request: stop_status
2024-02-13 00:37:20,462 INFO    Thread-12 :10788 [dir_watcher.py:_on_file_modified():230] file/dir modified: D:\jichuang\CNN\mydata\wandb\run-20240213_002618-1j1aaaj0\files\output.log
2024-02-13 00:37:20,924 DEBUG   HandlerThread:10788 [handler.py:handle_request():130] handle_request: stop_status
2024-02-13 00:37:20,924 DEBUG   SenderThread:10788 [sender.py:send_request():252] send_request: stop_status
2024-02-13 00:37:26,600 DEBUG   SenderThread:10788 [sender.py:send():238] send: stats
2024-02-13 00:37:36,482 DEBUG   HandlerThread:10788 [handler.py:handle_request():130] handle_request: stop_status
2024-02-13 00:37:36,482 DEBUG   SenderThread:10788 [sender.py:send_request():252] send_request: stop_status
2024-02-13 00:37:52,018 DEBUG   HandlerThread:10788 [handler.py:handle_request():130] handle_request: stop_status
2024-02-13 00:37:52,018 DEBUG   SenderThread:10788 [sender.py:send_request():252] send_request: stop_status
2024-02-13 00:37:59,056 INFO    Thread-12 :10788 [dir_watcher.py:_on_file_modified():230] file/dir modified: D:\jichuang\CNN\mydata\wandb\run-20240213_002618-1j1aaaj0\files\output.log
2024-02-13 00:38:02,129 DEBUG   SenderThread:10788 [sender.py:send():238] send: stats
2024-02-13 00:38:07,548 DEBUG   HandlerThread:10788 [handler.py:handle_request():130] handle_request: stop_status
2024-02-13 00:38:07,549 DEBUG   SenderThread:10788 [sender.py:send_request():252] send_request: stop_status
2024-02-13 00:38:23,038 DEBUG   HandlerThread:10788 [handler.py:handle_request():130] handle_request: stop_status
2024-02-13 00:38:23,039 DEBUG   SenderThread:10788 [sender.py:send_request():252] send_request: stop_status
2024-02-13 00:38:36,792 INFO    Thread-12 :10788 [dir_watcher.py:_on_file_modified():230] file/dir modified: D:\jichuang\CNN\mydata\wandb\run-20240213_002618-1j1aaaj0\files\output.log
2024-02-13 00:38:37,868 DEBUG   SenderThread:10788 [sender.py:send():238] send: stats
2024-02-13 00:38:38,569 DEBUG   HandlerThread:10788 [handler.py:handle_request():130] handle_request: stop_status
2024-02-13 00:38:38,569 DEBUG   SenderThread:10788 [sender.py:send_request():252] send_request: stop_status
2024-02-13 00:38:54,020 DEBUG   HandlerThread:10788 [handler.py:handle_request():130] handle_request: stop_status
2024-02-13 00:38:54,021 DEBUG   SenderThread:10788 [sender.py:send_request():252] send_request: stop_status
2024-02-13 00:39:09,447 DEBUG   HandlerThread:10788 [handler.py:handle_request():130] handle_request: stop_status
2024-02-13 00:39:09,448 DEBUG   SenderThread:10788 [sender.py:send_request():252] send_request: stop_status
2024-02-13 00:39:09,520 INFO    Thread-12 :10788 [dir_watcher.py:_on_file_modified():230] file/dir modified: D:\jichuang\CNN\mydata\wandb\run-20240213_002618-1j1aaaj0\files\output.log
2024-02-13 00:39:13,108 DEBUG   SenderThread:10788 [sender.py:send():238] send: stats
2024-02-13 00:39:24,976 DEBUG   HandlerThread:10788 [handler.py:handle_request():130] handle_request: stop_status
2024-02-13 00:39:24,977 DEBUG   SenderThread:10788 [sender.py:send_request():252] send_request: stop_status
2024-02-13 00:39:40,490 DEBUG   HandlerThread:10788 [handler.py:handle_request():130] handle_request: stop_status
2024-02-13 00:39:40,491 DEBUG   SenderThread:10788 [sender.py:send_request():252] send_request: stop_status
2024-02-13 00:39:48,228 INFO    Thread-12 :10788 [dir_watcher.py:_on_file_modified():230] file/dir modified: D:\jichuang\CNN\mydata\wandb\run-20240213_002618-1j1aaaj0\files\output.log
2024-02-13 00:39:48,688 DEBUG   SenderThread:10788 [sender.py:send():238] send: stats
2024-02-13 00:39:55,937 DEBUG   HandlerThread:10788 [handler.py:handle_request():130] handle_request: stop_status
2024-02-13 00:39:55,938 DEBUG   SenderThread:10788 [sender.py:send_request():252] send_request: stop_status
2024-02-13 00:40:11,457 DEBUG   HandlerThread:10788 [handler.py:handle_request():130] handle_request: stop_status
2024-02-13 00:40:11,458 DEBUG   SenderThread:10788 [sender.py:send_request():252] send_request: stop_status
2024-02-13 00:40:23,939 INFO    Thread-12 :10788 [dir_watcher.py:_on_file_modified():230] file/dir modified: D:\jichuang\CNN\mydata\wandb\run-20240213_002618-1j1aaaj0\files\output.log
2024-02-13 00:40:24,306 DEBUG   SenderThread:10788 [sender.py:send():238] send: stats
2024-02-13 00:40:26,963 DEBUG   HandlerThread:10788 [handler.py:handle_request():130] handle_request: stop_status
2024-02-13 00:40:26,964 DEBUG   SenderThread:10788 [sender.py:send_request():252] send_request: stop_status
2024-02-13 00:40:42,475 DEBUG   HandlerThread:10788 [handler.py:handle_request():130] handle_request: stop_status
2024-02-13 00:40:42,476 DEBUG   SenderThread:10788 [sender.py:send_request():252] send_request: stop_status
2024-02-13 00:40:57,979 DEBUG   HandlerThread:10788 [handler.py:handle_request():130] handle_request: stop_status
2024-02-13 00:40:57,980 DEBUG   SenderThread:10788 [sender.py:send_request():252] send_request: stop_status
2024-02-13 00:41:00,378 DEBUG   SenderThread:10788 [sender.py:send():238] send: stats
2024-02-13 00:41:06,813 INFO    Thread-12 :10788 [dir_watcher.py:_on_file_modified():230] file/dir modified: D:\jichuang\CNN\mydata\wandb\run-20240213_002618-1j1aaaj0\files\output.log
2024-02-13 00:41:13,491 DEBUG   HandlerThread:10788 [handler.py:handle_request():130] handle_request: stop_status
2024-02-13 00:41:13,492 DEBUG   SenderThread:10788 [sender.py:send_request():252] send_request: stop_status
2024-02-13 00:41:29,079 DEBUG   HandlerThread:10788 [handler.py:handle_request():130] handle_request: stop_status
2024-02-13 00:41:29,079 DEBUG   SenderThread:10788 [sender.py:send_request():252] send_request: stop_status
2024-02-13 00:41:37,259 DEBUG   SenderThread:10788 [sender.py:send():238] send: stats
2024-02-13 00:41:44,675 DEBUG   HandlerThread:10788 [handler.py:handle_request():130] handle_request: stop_status
2024-02-13 00:41:44,675 DEBUG   SenderThread:10788 [sender.py:send_request():252] send_request: stop_status
2024-02-13 00:41:52,712 INFO    Thread-12 :10788 [dir_watcher.py:_on_file_modified():230] file/dir modified: D:\jichuang\CNN\mydata\wandb\run-20240213_002618-1j1aaaj0\files\output.log
2024-02-13 00:42:00,110 DEBUG   HandlerThread:10788 [handler.py:handle_request():130] handle_request: stop_status
2024-02-13 00:42:00,111 DEBUG   SenderThread:10788 [sender.py:send_request():252] send_request: stop_status
2024-02-13 00:42:14,087 DEBUG   SenderThread:10788 [sender.py:send():238] send: stats
2024-02-13 00:42:15,627 DEBUG   HandlerThread:10788 [handler.py:handle_request():130] handle_request: stop_status
2024-02-13 00:42:15,628 DEBUG   SenderThread:10788 [sender.py:send_request():252] send_request: stop_status
2024-02-13 00:42:31,060 DEBUG   HandlerThread:10788 [handler.py:handle_request():130] handle_request: stop_status
2024-02-13 00:42:31,060 DEBUG   SenderThread:10788 [sender.py:send_request():252] send_request: stop_status
2024-02-13 00:42:39,812 INFO    Thread-12 :10788 [dir_watcher.py:_on_file_modified():230] file/dir modified: D:\jichuang\CNN\mydata\wandb\run-20240213_002618-1j1aaaj0\files\output.log
2024-02-13 00:42:41,548 ERROR   Thread-15 :10788 [internal_api.py:upload_file():1574] upload_file exception https://storage.googleapis.com/wandb-production.appspot.com/zhang-long/YOLOv8/1j1aaaj0/wandb-metadata.json?Expires=1707841619&GoogleAccessId=gorilla-files-url-signer-man%40wandb-production.iam.gserviceaccount.com&Signature=cZf8JvwvlyEan783%2FoIdBDuP%2FMRPKSJL8%2BJSgcHjEItD5k2%2FF7eKrUZ7lgys4kV2WsnuLKpQ5HnMsXpghu3%2FknwXChnrl1%2F0nA2B94diUHh2Uhfri%2BB5ySqP8gLS0rrstUyOyZStcDvpGbHoEOU39Bfe5R27RJ443lezMxVhCVVj9l2dEtnfHoyClDIBDQKJRW596k7G%2BOSXaA05gYm2S%2FFe9%2FXuFhKmtXBM9KC5LZy02%2FmmQolIV1%2F5KVe%2BbB7AuXJxrsuA%2FnvuWC4oj5wjPLIcueBkI5r6wmlTuRs4kmsq3UFS%2FEp1AzlXrAleSUkZeR41A8wIZML%2FdAYh4m8IwQ%3D%3D HTTPSConnectionPool(host='storage.googleapis.com', port=443): Max retries exceeded with url: /wandb-production.appspot.com/zhang-long/YOLOv8/1j1aaaj0/wandb-metadata.json?Expires=1707841619&GoogleAccessId=gorilla-files-url-signer-man%40wandb-production.iam.gserviceaccount.com&Signature=cZf8JvwvlyEan783%2FoIdBDuP%2FMRPKSJL8%2BJSgcHjEItD5k2%2FF7eKrUZ7lgys4kV2WsnuLKpQ5HnMsXpghu3%2FknwXChnrl1%2F0nA2B94diUHh2Uhfri%2BB5ySqP8gLS0rrstUyOyZStcDvpGbHoEOU39Bfe5R27RJ443lezMxVhCVVj9l2dEtnfHoyClDIBDQKJRW596k7G%2BOSXaA05gYm2S%2FFe9%2FXuFhKmtXBM9KC5LZy02%2FmmQolIV1%2F5KVe%2BbB7AuXJxrsuA%2FnvuWC4oj5wjPLIcueBkI5r6wmlTuRs4kmsq3UFS%2FEp1AzlXrAleSUkZeR41A8wIZML%2FdAYh4m8IwQ%3D%3D (Caused by NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x0000014CF5590100>: Failed to resolve 'storage.googleapis.com' ([Errno 11004] getaddrinfo failed)"))
2024-02-13 00:42:46,618 DEBUG   HandlerThread:10788 [handler.py:handle_request():130] handle_request: stop_status
2024-02-13 00:42:46,619 DEBUG   SenderThread:10788 [sender.py:send_request():252] send_request: stop_status
2024-02-13 00:42:50,741 DEBUG   SenderThread:10788 [sender.py:send():238] send: stats
2024-02-13 00:43:02,060 DEBUG   HandlerThread:10788 [handler.py:handle_request():130] handle_request: stop_status
2024-02-13 00:43:02,060 DEBUG   SenderThread:10788 [sender.py:send_request():252] send_request: stop_status
2024-02-13 00:43:17,490 INFO    Thread-12 :10788 [dir_watcher.py:_on_file_modified():230] file/dir modified: D:\jichuang\CNN\mydata\wandb\run-20240213_002618-1j1aaaj0\files\output.log
2024-02-13 00:43:20,551 DEBUG   HandlerThread:10788 [handler.py:handle_request():130] handle_request: stop_status
2024-02-13 00:43:20,552 DEBUG   SenderThread:10788 [sender.py:send_request():252] send_request: stop_status
2024-02-13 00:43:26,460 DEBUG   SenderThread:10788 [sender.py:send():238] send: stats
2024-02-13 00:43:36,079 DEBUG   HandlerThread:10788 [handler.py:handle_request():130] handle_request: stop_status
2024-02-13 00:43:36,079 DEBUG   SenderThread:10788 [sender.py:send_request():252] send_request: stop_status
2024-02-13 00:43:51,584 DEBUG   HandlerThread:10788 [handler.py:handle_request():130] handle_request: stop_status
2024-02-13 00:43:51,584 DEBUG   SenderThread:10788 [sender.py:send_request():252] send_request: stop_status
2024-02-13 00:43:56,228 INFO    Thread-12 :10788 [dir_watcher.py:_on_file_modified():230] file/dir modified: D:\jichuang\CNN\mydata\wandb\run-20240213_002618-1j1aaaj0\files\output.log
2024-02-13 00:44:02,309 DEBUG   SenderThread:10788 [sender.py:send():238] send: stats
2024-02-13 00:44:06,982 DEBUG   HandlerThread:10788 [handler.py:handle_request():130] handle_request: stop_status
2024-02-13 00:44:06,983 DEBUG   SenderThread:10788 [sender.py:send_request():252] send_request: stop_status
2024-02-13 00:44:22,515 DEBUG   HandlerThread:10788 [handler.py:handle_request():130] handle_request: stop_status
2024-02-13 00:44:22,516 DEBUG   SenderThread:10788 [sender.py:send_request():252] send_request: stop_status
2024-02-13 00:44:34,023 INFO    Thread-12 :10788 [dir_watcher.py:_on_file_modified():230] file/dir modified: D:\jichuang\CNN\mydata\wandb\run-20240213_002618-1j1aaaj0\files\output.log
2024-02-13 00:44:37,990 DEBUG   HandlerThread:10788 [handler.py:handle_request():130] handle_request: stop_status
2024-02-13 00:44:37,990 DEBUG   SenderThread:10788 [sender.py:send_request():252] send_request: stop_status
2024-02-13 00:44:38,446 DEBUG   SenderThread:10788 [sender.py:send():238] send: stats
2024-02-13 00:44:53,480 DEBUG   HandlerThread:10788 [handler.py:handle_request():130] handle_request: stop_status
2024-02-13 00:44:53,480 DEBUG   SenderThread:10788 [sender.py:send_request():252] send_request: stop_status
2024-02-13 00:45:08,654 INFO    Thread-12 :10788 [dir_watcher.py:_on_file_modified():230] file/dir modified: D:\jichuang\CNN\mydata\wandb\run-20240213_002618-1j1aaaj0\files\output.log
2024-02-13 00:45:08,998 DEBUG   HandlerThread:10788 [handler.py:handle_request():130] handle_request: stop_status
2024-02-13 00:45:08,999 DEBUG   SenderThread:10788 [sender.py:send_request():252] send_request: stop_status
2024-02-13 00:45:13,556 DEBUG   SenderThread:10788 [sender.py:send():238] send: stats
2024-02-13 00:45:24,542 DEBUG   HandlerThread:10788 [handler.py:handle_request():130] handle_request: stop_status
2024-02-13 00:45:24,542 DEBUG   SenderThread:10788 [sender.py:send_request():252] send_request: stop_status
2024-02-13 00:45:39,991 DEBUG   HandlerThread:10788 [handler.py:handle_request():130] handle_request: stop_status
2024-02-13 00:45:39,992 DEBUG   SenderThread:10788 [sender.py:send_request():252] send_request: stop_status
2024-02-13 00:45:49,488 INFO    Thread-12 :10788 [dir_watcher.py:_on_file_modified():230] file/dir modified: D:\jichuang\CNN\mydata\wandb\run-20240213_002618-1j1aaaj0\files\output.log
2024-02-13 00:45:49,964 DEBUG   SenderThread:10788 [sender.py:send():238] send: stats
2024-02-13 00:45:55,397 DEBUG   HandlerThread:10788 [handler.py:handle_request():130] handle_request: stop_status
2024-02-13 00:45:55,397 DEBUG   SenderThread:10788 [sender.py:send_request():252] send_request: stop_status
2024-02-13 00:46:10,859 DEBUG   HandlerThread:10788 [handler.py:handle_request():130] handle_request: stop_status
2024-02-13 00:46:10,860 DEBUG   SenderThread:10788 [sender.py:send_request():252] send_request: stop_status
2024-02-13 00:46:25,856 DEBUG   SenderThread:10788 [sender.py:send():238] send: stats
2024-02-13 00:46:26,319 DEBUG   HandlerThread:10788 [handler.py:handle_request():130] handle_request: stop_status
2024-02-13 00:46:26,319 DEBUG   SenderThread:10788 [sender.py:send_request():252] send_request: stop_status
2024-02-13 00:46:27,160 INFO    Thread-12 :10788 [dir_watcher.py:_on_file_modified():230] file/dir modified: D:\jichuang\CNN\mydata\wandb\run-20240213_002618-1j1aaaj0\files\output.log
2024-02-13 00:46:41,840 DEBUG   HandlerThread:10788 [handler.py:handle_request():130] handle_request: stop_status
2024-02-13 00:46:41,841 DEBUG   SenderThread:10788 [sender.py:send_request():252] send_request: stop_status
2024-02-13 00:46:57,260 DEBUG   HandlerThread:10788 [handler.py:handle_request():130] handle_request: stop_status
2024-02-13 00:46:57,260 DEBUG   SenderThread:10788 [sender.py:send_request():252] send_request: stop_status
2024-02-13 00:47:01,259 DEBUG   SenderThread:10788 [sender.py:send():238] send: stats
2024-02-13 00:47:01,793 INFO    Thread-12 :10788 [dir_watcher.py:_on_file_modified():230] file/dir modified: D:\jichuang\CNN\mydata\wandb\run-20240213_002618-1j1aaaj0\files\output.log
2024-02-13 00:47:12,749 DEBUG   HandlerThread:10788 [handler.py:handle_request():130] handle_request: stop_status
2024-02-13 00:47:12,749 DEBUG   SenderThread:10788 [sender.py:send_request():252] send_request: stop_status
2024-02-13 00:47:28,255 DEBUG   HandlerThread:10788 [handler.py:handle_request():130] handle_request: stop_status
2024-02-13 00:47:28,256 DEBUG   SenderThread:10788 [sender.py:send_request():252] send_request: stop_status
2024-02-13 00:47:36,993 DEBUG   SenderThread:10788 [sender.py:send():238] send: stats
2024-02-13 00:47:40,427 INFO    Thread-12 :10788 [dir_watcher.py:_on_file_modified():230] file/dir modified: D:\jichuang\CNN\mydata\wandb\run-20240213_002618-1j1aaaj0\files\output.log
2024-02-13 00:47:43,794 DEBUG   HandlerThread:10788 [handler.py:handle_request():130] handle_request: stop_status
2024-02-13 00:47:43,794 DEBUG   SenderThread:10788 [sender.py:send_request():252] send_request: stop_status
2024-02-13 00:47:59,304 DEBUG   HandlerThread:10788 [handler.py:handle_request():130] handle_request: stop_status
2024-02-13 00:47:59,304 DEBUG   SenderThread:10788 [sender.py:send_request():252] send_request: stop_status
2024-02-13 00:48:12,349 DEBUG   SenderThread:10788 [sender.py:send():238] send: stats
2024-02-13 00:48:13,944 INFO    Thread-12 :10788 [dir_watcher.py:_on_file_modified():230] file/dir modified: D:\jichuang\CNN\mydata\wandb\run-20240213_002618-1j1aaaj0\files\output.log
2024-02-13 00:48:14,777 DEBUG   HandlerThread:10788 [handler.py:handle_request():130] handle_request: stop_status
2024-02-13 00:48:14,777 DEBUG   SenderThread:10788 [sender.py:send_request():252] send_request: stop_status
2024-02-13 00:48:28,380 ERROR   Thread-15 :10788 [internal_api.py:upload_file():1574] upload_file exception https://storage.googleapis.com/wandb-production.appspot.com/zhang-long/YOLOv8/1j1aaaj0/wandb-metadata.json?Expires=1707841619&GoogleAccessId=gorilla-files-url-signer-man%40wandb-production.iam.gserviceaccount.com&Signature=cZf8JvwvlyEan783%2FoIdBDuP%2FMRPKSJL8%2BJSgcHjEItD5k2%2FF7eKrUZ7lgys4kV2WsnuLKpQ5HnMsXpghu3%2FknwXChnrl1%2F0nA2B94diUHh2Uhfri%2BB5ySqP8gLS0rrstUyOyZStcDvpGbHoEOU39Bfe5R27RJ443lezMxVhCVVj9l2dEtnfHoyClDIBDQKJRW596k7G%2BOSXaA05gYm2S%2FFe9%2FXuFhKmtXBM9KC5LZy02%2FmmQolIV1%2F5KVe%2BbB7AuXJxrsuA%2FnvuWC4oj5wjPLIcueBkI5r6wmlTuRs4kmsq3UFS%2FEp1AzlXrAleSUkZeR41A8wIZML%2FdAYh4m8IwQ%3D%3D HTTPSConnectionPool(host='storage.googleapis.com', port=443): Max retries exceeded with url: /wandb-production.appspot.com/zhang-long/YOLOv8/1j1aaaj0/wandb-metadata.json?Expires=1707841619&GoogleAccessId=gorilla-files-url-signer-man%40wandb-production.iam.gserviceaccount.com&Signature=cZf8JvwvlyEan783%2FoIdBDuP%2FMRPKSJL8%2BJSgcHjEItD5k2%2FF7eKrUZ7lgys4kV2WsnuLKpQ5HnMsXpghu3%2FknwXChnrl1%2F0nA2B94diUHh2Uhfri%2BB5ySqP8gLS0rrstUyOyZStcDvpGbHoEOU39Bfe5R27RJ443lezMxVhCVVj9l2dEtnfHoyClDIBDQKJRW596k7G%2BOSXaA05gYm2S%2FFe9%2FXuFhKmtXBM9KC5LZy02%2FmmQolIV1%2F5KVe%2BbB7AuXJxrsuA%2FnvuWC4oj5wjPLIcueBkI5r6wmlTuRs4kmsq3UFS%2FEp1AzlXrAleSUkZeR41A8wIZML%2FdAYh4m8IwQ%3D%3D (Caused by NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x0000014CF549FB80>: Failed to resolve 'storage.googleapis.com' ([Errno 11004] getaddrinfo failed)"))
2024-02-13 00:48:30,304 DEBUG   HandlerThread:10788 [handler.py:handle_request():130] handle_request: stop_status
2024-02-13 00:48:30,304 DEBUG   SenderThread:10788 [sender.py:send_request():252] send_request: stop_status
2024-02-13 00:48:45,881 DEBUG   HandlerThread:10788 [handler.py:handle_request():130] handle_request: stop_status
2024-02-13 00:48:45,889 DEBUG   SenderThread:10788 [sender.py:send_request():252] send_request: stop_status
2024-02-13 00:48:48,327 DEBUG   SenderThread:10788 [sender.py:send():238] send: stats
2024-02-13 00:48:52,498 INFO    Thread-12 :10788 [dir_watcher.py:_on_file_modified():230] file/dir modified: D:\jichuang\CNN\mydata\wandb\run-20240213_002618-1j1aaaj0\files\output.log
2024-02-13 00:49:01,356 DEBUG   HandlerThread:10788 [handler.py:handle_request():130] handle_request: stop_status
2024-02-13 00:49:01,357 DEBUG   SenderThread:10788 [sender.py:send_request():252] send_request: stop_status
2024-02-13 00:49:16,867 DEBUG   HandlerThread:10788 [handler.py:handle_request():130] handle_request: stop_status
2024-02-13 00:49:16,867 DEBUG   SenderThread:10788 [sender.py:send_request():252] send_request: stop_status
2024-02-13 00:49:23,316 DEBUG   SenderThread:10788 [sender.py:send():238] send: stats
2024-02-13 00:49:31,215 INFO    Thread-12 :10788 [dir_watcher.py:_on_file_modified():230] file/dir modified: D:\jichuang\CNN\mydata\wandb\run-20240213_002618-1j1aaaj0\files\output.log
2024-02-13 00:49:32,408 DEBUG   HandlerThread:10788 [handler.py:handle_request():130] handle_request: stop_status
2024-02-13 00:49:32,409 DEBUG   SenderThread:10788 [sender.py:send_request():252] send_request: stop_status
2024-02-13 00:49:49,672 DEBUG   HandlerThread:10788 [handler.py:handle_request():130] handle_request: stop_status
2024-02-13 00:49:49,673 DEBUG   SenderThread:10788 [sender.py:send_request():252] send_request: stop_status
2024-02-13 00:49:58,861 DEBUG   SenderThread:10788 [sender.py:send():238] send: stats
2024-02-13 00:50:04,885 INFO    Thread-12 :10788 [dir_watcher.py:_on_file_modified():230] file/dir modified: D:\jichuang\CNN\mydata\wandb\run-20240213_002618-1j1aaaj0\files\output.log
2024-02-13 00:50:05,155 DEBUG   HandlerThread:10788 [handler.py:handle_request():130] handle_request: stop_status
2024-02-13 00:50:05,156 DEBUG   SenderThread:10788 [sender.py:send_request():252] send_request: stop_status
2024-02-13 00:50:20,626 DEBUG   HandlerThread:10788 [handler.py:handle_request():130] handle_request: stop_status
2024-02-13 00:50:20,626 DEBUG   SenderThread:10788 [sender.py:send_request():252] send_request: stop_status
2024-02-13 00:50:35,339 DEBUG   SenderThread:10788 [sender.py:send():238] send: stats
2024-02-13 00:50:36,091 DEBUG   HandlerThread:10788 [handler.py:handle_request():130] handle_request: stop_status
2024-02-13 00:50:36,091 DEBUG   SenderThread:10788 [sender.py:send_request():252] send_request: stop_status
2024-02-13 00:50:47,732 INFO    Thread-12 :10788 [dir_watcher.py:_on_file_modified():230] file/dir modified: D:\jichuang\CNN\mydata\wandb\run-20240213_002618-1j1aaaj0\files\output.log
2024-02-13 00:50:51,609 DEBUG   HandlerThread:10788 [handler.py:handle_request():130] handle_request: stop_status
2024-02-13 00:50:51,610 DEBUG   SenderThread:10788 [sender.py:send_request():252] send_request: stop_status
2024-02-13 00:51:07,075 DEBUG   HandlerThread:10788 [handler.py:handle_request():130] handle_request: stop_status
2024-02-13 00:51:07,076 DEBUG   SenderThread:10788 [sender.py:send_request():252] send_request: stop_status
2024-02-13 00:51:11,522 DEBUG   SenderThread:10788 [sender.py:send():238] send: stats
2024-02-13 00:51:22,566 DEBUG   HandlerThread:10788 [handler.py:handle_request():130] handle_request: stop_status
2024-02-13 00:51:22,566 DEBUG   SenderThread:10788 [sender.py:send_request():252] send_request: stop_status
2024-02-13 00:51:28,483 INFO    Thread-12 :10788 [dir_watcher.py:_on_file_modified():230] file/dir modified: D:\jichuang\CNN\mydata\wandb\run-20240213_002618-1j1aaaj0\files\output.log
2024-02-13 00:51:37,983 DEBUG   HandlerThread:10788 [handler.py:handle_request():130] handle_request: stop_status
2024-02-13 00:51:37,984 DEBUG   SenderThread:10788 [sender.py:send_request():252] send_request: stop_status
2024-02-13 00:51:47,122 DEBUG   SenderThread:10788 [sender.py:send():238] send: stats
2024-02-13 00:51:53,424 DEBUG   HandlerThread:10788 [handler.py:handle_request():130] handle_request: stop_status
2024-02-13 00:51:53,424 DEBUG   SenderThread:10788 [sender.py:send_request():252] send_request: stop_status
2024-02-13 00:52:04,097 INFO    Thread-12 :10788 [dir_watcher.py:_on_file_modified():230] file/dir modified: D:\jichuang\CNN\mydata\wandb\run-20240213_002618-1j1aaaj0\files\output.log
2024-02-13 00:52:08,968 DEBUG   HandlerThread:10788 [handler.py:handle_request():130] handle_request: stop_status
2024-02-13 00:52:08,968 DEBUG   SenderThread:10788 [sender.py:send_request():252] send_request: stop_status
2024-02-13 00:52:22,523 DEBUG   SenderThread:10788 [sender.py:send():238] send: stats
2024-02-13 00:52:24,490 DEBUG   HandlerThread:10788 [handler.py:handle_request():130] handle_request: stop_status
2024-02-13 00:52:24,490 DEBUG   SenderThread:10788 [sender.py:send_request():252] send_request: stop_status
2024-02-13 00:52:39,971 DEBUG   HandlerThread:10788 [handler.py:handle_request():130] handle_request: stop_status
2024-02-13 00:52:39,971 DEBUG   SenderThread:10788 [sender.py:send_request():252] send_request: stop_status
2024-02-13 00:52:40,851 INFO    Thread-12 :10788 [dir_watcher.py:_on_file_modified():230] file/dir modified: D:\jichuang\CNN\mydata\wandb\run-20240213_002618-1j1aaaj0\files\output.log
2024-02-13 00:52:55,510 DEBUG   HandlerThread:10788 [handler.py:handle_request():130] handle_request: stop_status
2024-02-13 00:52:55,510 DEBUG   SenderThread:10788 [sender.py:send_request():252] send_request: stop_status
2024-02-13 00:52:58,291 DEBUG   SenderThread:10788 [sender.py:send():238] send: stats
2024-02-13 00:53:11,001 DEBUG   HandlerThread:10788 [handler.py:handle_request():130] handle_request: stop_status
2024-02-13 00:53:11,002 DEBUG   SenderThread:10788 [sender.py:send_request():252] send_request: stop_status
2024-02-13 00:53:16,508 INFO    Thread-12 :10788 [dir_watcher.py:_on_file_modified():230] file/dir modified: D:\jichuang\CNN\mydata\wandb\run-20240213_002618-1j1aaaj0\files\output.log
2024-02-13 00:53:26,419 DEBUG   HandlerThread:10788 [handler.py:handle_request():130] handle_request: stop_status
2024-02-13 00:53:26,419 DEBUG   SenderThread:10788 [sender.py:send_request():252] send_request: stop_status
2024-02-13 00:53:33,976 DEBUG   SenderThread:10788 [sender.py:send():238] send: stats
2024-02-13 00:53:41,895 DEBUG   HandlerThread:10788 [handler.py:handle_request():130] handle_request: stop_status
2024-02-13 00:53:41,896 DEBUG   SenderThread:10788 [sender.py:send_request():252] send_request: stop_status
2024-02-13 00:53:51,529 ERROR   Thread-15 :10788 [internal_api.py:upload_file():1574] upload_file exception https://storage.googleapis.com/wandb-production.appspot.com/zhang-long/YOLOv8/1j1aaaj0/wandb-metadata.json?Expires=1707841619&GoogleAccessId=gorilla-files-url-signer-man%40wandb-production.iam.gserviceaccount.com&Signature=cZf8JvwvlyEan783%2FoIdBDuP%2FMRPKSJL8%2BJSgcHjEItD5k2%2FF7eKrUZ7lgys4kV2WsnuLKpQ5HnMsXpghu3%2FknwXChnrl1%2F0nA2B94diUHh2Uhfri%2BB5ySqP8gLS0rrstUyOyZStcDvpGbHoEOU39Bfe5R27RJ443lezMxVhCVVj9l2dEtnfHoyClDIBDQKJRW596k7G%2BOSXaA05gYm2S%2FFe9%2FXuFhKmtXBM9KC5LZy02%2FmmQolIV1%2F5KVe%2BbB7AuXJxrsuA%2FnvuWC4oj5wjPLIcueBkI5r6wmlTuRs4kmsq3UFS%2FEp1AzlXrAleSUkZeR41A8wIZML%2FdAYh4m8IwQ%3D%3D HTTPSConnectionPool(host='storage.googleapis.com', port=443): Max retries exceeded with url: /wandb-production.appspot.com/zhang-long/YOLOv8/1j1aaaj0/wandb-metadata.json?Expires=1707841619&GoogleAccessId=gorilla-files-url-signer-man%40wandb-production.iam.gserviceaccount.com&Signature=cZf8JvwvlyEan783%2FoIdBDuP%2FMRPKSJL8%2BJSgcHjEItD5k2%2FF7eKrUZ7lgys4kV2WsnuLKpQ5HnMsXpghu3%2FknwXChnrl1%2F0nA2B94diUHh2Uhfri%2BB5ySqP8gLS0rrstUyOyZStcDvpGbHoEOU39Bfe5R27RJ443lezMxVhCVVj9l2dEtnfHoyClDIBDQKJRW596k7G%2BOSXaA05gYm2S%2FFe9%2FXuFhKmtXBM9KC5LZy02%2FmmQolIV1%2F5KVe%2BbB7AuXJxrsuA%2FnvuWC4oj5wjPLIcueBkI5r6wmlTuRs4kmsq3UFS%2FEp1AzlXrAleSUkZeR41A8wIZML%2FdAYh4m8IwQ%3D%3D (Caused by NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x0000014CF54C6A30>: Failed to resolve 'storage.googleapis.com' ([Errno 11004] getaddrinfo failed)"))
2024-02-13 00:53:55,140 INFO    Thread-12 :10788 [dir_watcher.py:_on_file_modified():230] file/dir modified: D:\jichuang\CNN\mydata\wandb\run-20240213_002618-1j1aaaj0\files\output.log
2024-02-13 00:53:57,407 DEBUG   HandlerThread:10788 [handler.py:handle_request():130] handle_request: stop_status
2024-02-13 00:53:57,408 DEBUG   SenderThread:10788 [sender.py:send_request():252] send_request: stop_status
2024-02-13 00:54:09,560 DEBUG   SenderThread:10788 [sender.py:send():238] send: stats
2024-02-13 00:54:12,869 DEBUG   HandlerThread:10788 [handler.py:handle_request():130] handle_request: stop_status
2024-02-13 00:54:12,870 DEBUG   SenderThread:10788 [sender.py:send_request():252] send_request: stop_status
2024-02-13 00:54:28,307 DEBUG   HandlerThread:10788 [handler.py:handle_request():130] handle_request: stop_status
2024-02-13 00:54:28,307 DEBUG   SenderThread:10788 [sender.py:send_request():252] send_request: stop_status
2024-02-13 00:54:32,066 INFO    Thread-12 :10788 [dir_watcher.py:_on_file_modified():230] file/dir modified: D:\jichuang\CNN\mydata\wandb\run-20240213_002618-1j1aaaj0\files\output.log
2024-02-13 00:54:43,817 DEBUG   HandlerThread:10788 [handler.py:handle_request():130] handle_request: stop_status
2024-02-13 00:54:43,817 DEBUG   SenderThread:10788 [sender.py:send_request():252] send_request: stop_status
2024-02-13 00:54:45,110 DEBUG   SenderThread:10788 [sender.py:send():238] send: stats
2024-02-13 00:54:59,263 DEBUG   HandlerThread:10788 [handler.py:handle_request():130] handle_request: stop_status
2024-02-13 00:54:59,263 DEBUG   SenderThread:10788 [sender.py:send_request():252] send_request: stop_status
2024-02-13 00:55:05,669 INFO    Thread-12 :10788 [dir_watcher.py:_on_file_modified():230] file/dir modified: D:\jichuang\CNN\mydata\wandb\run-20240213_002618-1j1aaaj0\files\output.log
2024-02-13 00:55:14,729 DEBUG   HandlerThread:10788 [handler.py:handle_request():130] handle_request: stop_status
2024-02-13 00:55:14,729 DEBUG   SenderThread:10788 [sender.py:send_request():252] send_request: stop_status
2024-02-13 00:55:20,125 DEBUG   SenderThread:10788 [sender.py:send():238] send: stats
2024-02-13 00:55:30,131 DEBUG   HandlerThread:10788 [handler.py:handle_request():130] handle_request: stop_status
2024-02-13 00:55:30,132 DEBUG   SenderThread:10788 [sender.py:send_request():252] send_request: stop_status
2024-02-13 00:55:44,298 INFO    Thread-12 :10788 [dir_watcher.py:_on_file_modified():230] file/dir modified: D:\jichuang\CNN\mydata\wandb\run-20240213_002618-1j1aaaj0\files\output.log
2024-02-13 00:55:45,541 DEBUG   HandlerThread:10788 [handler.py:handle_request():130] handle_request: stop_status
2024-02-13 00:55:45,542 DEBUG   SenderThread:10788 [sender.py:send_request():252] send_request: stop_status
2024-02-13 00:55:56,042 DEBUG   SenderThread:10788 [sender.py:send():238] send: stats
2024-02-13 00:56:00,993 DEBUG   HandlerThread:10788 [handler.py:handle_request():130] handle_request: stop_status
2024-02-13 00:56:00,994 DEBUG   SenderThread:10788 [sender.py:send_request():252] send_request: stop_status
2024-02-13 00:56:16,483 DEBUG   HandlerThread:10788 [handler.py:handle_request():130] handle_request: stop_status
2024-02-13 00:56:16,483 DEBUG   SenderThread:10788 [sender.py:send_request():252] send_request: stop_status
2024-02-13 00:56:24,010 INFO    Thread-12 :10788 [dir_watcher.py:_on_file_modified():230] file/dir modified: D:\jichuang\CNN\mydata\wandb\run-20240213_002618-1j1aaaj0\files\output.log
2024-02-13 00:56:32,019 DEBUG   HandlerThread:10788 [handler.py:handle_request():130] handle_request: stop_status
2024-02-13 00:56:32,028 DEBUG   SenderThread:10788 [sender.py:send_request():252] send_request: stop_status
2024-02-13 00:56:32,524 DEBUG   SenderThread:10788 [sender.py:send():238] send: stats
2024-02-13 00:56:47,540 DEBUG   HandlerThread:10788 [handler.py:handle_request():130] handle_request: stop_status
2024-02-13 00:56:47,541 DEBUG   SenderThread:10788 [sender.py:send_request():252] send_request: stop_status
2024-02-13 00:57:00,761 INFO    Thread-12 :10788 [dir_watcher.py:_on_file_modified():230] file/dir modified: D:\jichuang\CNN\mydata\wandb\run-20240213_002618-1j1aaaj0\files\output.log
2024-02-13 00:57:03,041 DEBUG   HandlerThread:10788 [handler.py:handle_request():130] handle_request: stop_status
2024-02-13 00:57:03,042 DEBUG   SenderThread:10788 [sender.py:send_request():252] send_request: stop_status
2024-02-13 00:57:07,514 DEBUG   SenderThread:10788 [sender.py:send():238] send: stats
2024-02-13 00:57:18,435 DEBUG   HandlerThread:10788 [handler.py:handle_request():130] handle_request: stop_status
2024-02-13 00:57:18,436 DEBUG   SenderThread:10788 [sender.py:send_request():252] send_request: stop_status
2024-02-13 00:57:33,913 DEBUG   HandlerThread:10788 [handler.py:handle_request():130] handle_request: stop_status
2024-02-13 00:57:33,914 DEBUG   SenderThread:10788 [sender.py:send_request():252] send_request: stop_status
2024-02-13 00:57:37,389 INFO    Thread-12 :10788 [dir_watcher.py:_on_file_modified():230] file/dir modified: D:\jichuang\CNN\mydata\wandb\run-20240213_002618-1j1aaaj0\files\output.log
2024-02-13 00:57:43,162 DEBUG   SenderThread:10788 [sender.py:send():238] send: stats
2024-02-13 00:57:49,426 DEBUG   HandlerThread:10788 [handler.py:handle_request():130] handle_request: stop_status
2024-02-13 00:57:49,426 DEBUG   SenderThread:10788 [sender.py:send_request():252] send_request: stop_status
2024-02-13 00:58:04,945 DEBUG   HandlerThread:10788 [handler.py:handle_request():130] handle_request: stop_status
2024-02-13 00:58:04,946 DEBUG   SenderThread:10788 [sender.py:send_request():252] send_request: stop_status
2024-02-13 00:58:11,010 INFO    Thread-12 :10788 [dir_watcher.py:_on_file_modified():230] file/dir modified: D:\jichuang\CNN\mydata\wandb\run-20240213_002618-1j1aaaj0\files\output.log
2024-02-13 00:58:18,695 DEBUG   SenderThread:10788 [sender.py:send():238] send: stats
2024-02-13 00:58:20,396 DEBUG   HandlerThread:10788 [handler.py:handle_request():130] handle_request: stop_status
2024-02-13 00:58:20,397 DEBUG   SenderThread:10788 [sender.py:send_request():252] send_request: stop_status
2024-02-13 00:58:35,889 DEBUG   HandlerThread:10788 [handler.py:handle_request():130] handle_request: stop_status
2024-02-13 00:58:35,890 DEBUG   SenderThread:10788 [sender.py:send_request():252] send_request: stop_status
2024-02-13 00:58:49,754 INFO    Thread-12 :10788 [dir_watcher.py:_on_file_modified():230] file/dir modified: D:\jichuang\CNN\mydata\wandb\run-20240213_002618-1j1aaaj0\files\output.log
2024-02-13 00:58:51,399 DEBUG   HandlerThread:10788 [handler.py:handle_request():130] handle_request: stop_status
2024-02-13 00:58:51,400 DEBUG   SenderThread:10788 [sender.py:send_request():252] send_request: stop_status
2024-02-13 00:58:54,518 DEBUG   SenderThread:10788 [sender.py:send():238] send: stats
2024-02-13 00:59:04,037 ERROR   Thread-15 :10788 [internal_api.py:upload_file():1574] upload_file exception https://storage.googleapis.com/wandb-production.appspot.com/zhang-long/YOLOv8/1j1aaaj0/wandb-metadata.json?Expires=1707841619&GoogleAccessId=gorilla-files-url-signer-man%40wandb-production.iam.gserviceaccount.com&Signature=cZf8JvwvlyEan783%2FoIdBDuP%2FMRPKSJL8%2BJSgcHjEItD5k2%2FF7eKrUZ7lgys4kV2WsnuLKpQ5HnMsXpghu3%2FknwXChnrl1%2F0nA2B94diUHh2Uhfri%2BB5ySqP8gLS0rrstUyOyZStcDvpGbHoEOU39Bfe5R27RJ443lezMxVhCVVj9l2dEtnfHoyClDIBDQKJRW596k7G%2BOSXaA05gYm2S%2FFe9%2FXuFhKmtXBM9KC5LZy02%2FmmQolIV1%2F5KVe%2BbB7AuXJxrsuA%2FnvuWC4oj5wjPLIcueBkI5r6wmlTuRs4kmsq3UFS%2FEp1AzlXrAleSUkZeR41A8wIZML%2FdAYh4m8IwQ%3D%3D HTTPSConnectionPool(host='storage.googleapis.com', port=443): Max retries exceeded with url: /wandb-production.appspot.com/zhang-long/YOLOv8/1j1aaaj0/wandb-metadata.json?Expires=1707841619&GoogleAccessId=gorilla-files-url-signer-man%40wandb-production.iam.gserviceaccount.com&Signature=cZf8JvwvlyEan783%2FoIdBDuP%2FMRPKSJL8%2BJSgcHjEItD5k2%2FF7eKrUZ7lgys4kV2WsnuLKpQ5HnMsXpghu3%2FknwXChnrl1%2F0nA2B94diUHh2Uhfri%2BB5ySqP8gLS0rrstUyOyZStcDvpGbHoEOU39Bfe5R27RJ443lezMxVhCVVj9l2dEtnfHoyClDIBDQKJRW596k7G%2BOSXaA05gYm2S%2FFe9%2FXuFhKmtXBM9KC5LZy02%2FmmQolIV1%2F5KVe%2BbB7AuXJxrsuA%2FnvuWC4oj5wjPLIcueBkI5r6wmlTuRs4kmsq3UFS%2FEp1AzlXrAleSUkZeR41A8wIZML%2FdAYh4m8IwQ%3D%3D (Caused by NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x0000014CF54BDC70>: Failed to resolve 'storage.googleapis.com' ([Errno 11004] getaddrinfo failed)"))
2024-02-13 00:59:06,868 DEBUG   HandlerThread:10788 [handler.py:handle_request():130] handle_request: stop_status
2024-02-13 00:59:06,868 DEBUG   SenderThread:10788 [sender.py:send_request():252] send_request: stop_status
2024-02-13 00:59:22,263 DEBUG   HandlerThread:10788 [handler.py:handle_request():130] handle_request: stop_status
2024-02-13 00:59:22,263 DEBUG   SenderThread:10788 [sender.py:send_request():252] send_request: stop_status
2024-02-13 00:59:26,418 INFO    Thread-12 :10788 [dir_watcher.py:_on_file_modified():230] file/dir modified: D:\jichuang\CNN\mydata\wandb\run-20240213_002618-1j1aaaj0\files\output.log
2024-02-13 00:59:30,070 DEBUG   SenderThread:10788 [sender.py:send():238] send: stats
2024-02-13 00:59:37,707 DEBUG   HandlerThread:10788 [handler.py:handle_request():130] handle_request: stop_status
2024-02-13 00:59:37,707 DEBUG   SenderThread:10788 [sender.py:send_request():252] send_request: stop_status
2024-02-13 00:59:53,157 DEBUG   HandlerThread:10788 [handler.py:handle_request():130] handle_request: stop_status
2024-02-13 00:59:53,157 DEBUG   SenderThread:10788 [sender.py:send_request():252] send_request: stop_status
2024-02-13 01:00:00,059 INFO    Thread-12 :10788 [dir_watcher.py:_on_file_modified():230] file/dir modified: D:\jichuang\CNN\mydata\wandb\run-20240213_002618-1j1aaaj0\files\output.log
2024-02-13 01:00:05,230 DEBUG   SenderThread:10788 [sender.py:send():238] send: stats
2024-02-13 01:00:08,599 DEBUG   HandlerThread:10788 [handler.py:handle_request():130] handle_request: stop_status
2024-02-13 01:00:08,600 DEBUG   SenderThread:10788 [sender.py:send_request():252] send_request: stop_status
2024-02-13 01:00:24,113 DEBUG   HandlerThread:10788 [handler.py:handle_request():130] handle_request: stop_status
2024-02-13 01:00:24,113 DEBUG   SenderThread:10788 [sender.py:send_request():252] send_request: stop_status
2024-02-13 01:00:38,792 INFO    Thread-12 :10788 [dir_watcher.py:_on_file_modified():230] file/dir modified: D:\jichuang\CNN\mydata\wandb\run-20240213_002618-1j1aaaj0\files\output.log
2024-02-13 01:00:39,589 DEBUG   HandlerThread:10788 [handler.py:handle_request():130] handle_request: stop_status
2024-02-13 01:00:39,590 DEBUG   SenderThread:10788 [sender.py:send_request():252] send_request: stop_status
2024-02-13 01:00:40,961 DEBUG   SenderThread:10788 [sender.py:send():238] send: stats
2024-02-13 01:00:55,071 DEBUG   HandlerThread:10788 [handler.py:handle_request():130] handle_request: stop_status
2024-02-13 01:00:55,071 DEBUG   SenderThread:10788 [sender.py:send_request():252] send_request: stop_status
2024-02-13 01:01:10,581 DEBUG   HandlerThread:10788 [handler.py:handle_request():130] handle_request: stop_status
2024-02-13 01:01:10,581 DEBUG   SenderThread:10788 [sender.py:send_request():252] send_request: stop_status
2024-02-13 01:01:17,046 DEBUG   SenderThread:10788 [sender.py:send():238] send: stats
2024-02-13 01:01:18,665 INFO    Thread-12 :10788 [dir_watcher.py:_on_file_modified():230] file/dir modified: D:\jichuang\CNN\mydata\wandb\run-20240213_002618-1j1aaaj0\files\output.log
2024-02-13 01:01:26,084 DEBUG   HandlerThread:10788 [handler.py:handle_request():130] handle_request: stop_status
2024-02-13 01:01:26,084 DEBUG   SenderThread:10788 [sender.py:send_request():252] send_request: stop_status
2024-02-13 01:01:41,545 DEBUG   HandlerThread:10788 [handler.py:handle_request():130] handle_request: stop_status
2024-02-13 01:01:41,545 DEBUG   SenderThread:10788 [sender.py:send_request():252] send_request: stop_status
2024-02-13 01:01:53,123 DEBUG   SenderThread:10788 [sender.py:send():238] send: stats
2024-02-13 01:01:55,256 INFO    Thread-12 :10788 [dir_watcher.py:_on_file_modified():230] file/dir modified: D:\jichuang\CNN\mydata\wandb\run-20240213_002618-1j1aaaj0\files\output.log
2024-02-13 01:01:57,052 DEBUG   HandlerThread:10788 [handler.py:handle_request():130] handle_request: stop_status
2024-02-13 01:01:57,052 DEBUG   SenderThread:10788 [sender.py:send_request():252] send_request: stop_status
2024-02-13 01:02:12,510 DEBUG   HandlerThread:10788 [handler.py:handle_request():130] handle_request: stop_status
2024-02-13 01:02:12,511 DEBUG   SenderThread:10788 [sender.py:send_request():252] send_request: stop_status
2024-02-13 01:02:28,013 DEBUG   HandlerThread:10788 [handler.py:handle_request():130] handle_request: stop_status
2024-02-13 01:02:28,014 DEBUG   SenderThread:10788 [sender.py:send_request():252] send_request: stop_status
2024-02-13 01:02:28,795 DEBUG   SenderThread:10788 [sender.py:send():238] send: stats
2024-02-13 01:02:34,153 INFO    Thread-12 :10788 [dir_watcher.py:_on_file_modified():230] file/dir modified: D:\jichuang\CNN\mydata\wandb\run-20240213_002618-1j1aaaj0\files\output.log
2024-02-13 01:02:43,476 DEBUG   HandlerThread:10788 [handler.py:handle_request():130] handle_request: stop_status
2024-02-13 01:02:43,476 DEBUG   SenderThread:10788 [sender.py:send_request():252] send_request: stop_status
2024-02-13 01:02:58,954 DEBUG   HandlerThread:10788 [handler.py:handle_request():130] handle_request: stop_status
2024-02-13 01:02:58,954 DEBUG   SenderThread:10788 [sender.py:send_request():252] send_request: stop_status
2024-02-13 01:03:04,191 DEBUG   SenderThread:10788 [sender.py:send():238] send: stats
2024-02-13 01:03:07,714 INFO    Thread-12 :10788 [dir_watcher.py:_on_file_modified():230] file/dir modified: D:\jichuang\CNN\mydata\wandb\run-20240213_002618-1j1aaaj0\files\output.log
2024-02-13 01:03:14,436 DEBUG   HandlerThread:10788 [handler.py:handle_request():130] handle_request: stop_status
2024-02-13 01:03:14,436 DEBUG   SenderThread:10788 [sender.py:send_request():252] send_request: stop_status
2024-02-13 01:03:29,876 DEBUG   HandlerThread:10788 [handler.py:handle_request():130] handle_request: stop_status
2024-02-13 01:03:29,877 DEBUG   SenderThread:10788 [sender.py:send_request():252] send_request: stop_status
2024-02-13 01:03:40,054 DEBUG   SenderThread:10788 [sender.py:send():238] send: stats
2024-02-13 01:03:45,321 DEBUG   HandlerThread:10788 [handler.py:handle_request():130] handle_request: stop_status
2024-02-13 01:03:45,321 DEBUG   SenderThread:10788 [sender.py:send_request():252] send_request: stop_status
2024-02-13 01:03:46,478 INFO    Thread-12 :10788 [dir_watcher.py:_on_file_modified():230] file/dir modified: D:\jichuang\CNN\mydata\wandb\run-20240213_002618-1j1aaaj0\files\output.log
2024-02-13 01:04:00,743 DEBUG   HandlerThread:10788 [handler.py:handle_request():130] handle_request: stop_status
2024-02-13 01:04:00,744 DEBUG   SenderThread:10788 [sender.py:send_request():252] send_request: stop_status
2024-02-13 01:04:15,363 DEBUG   SenderThread:10788 [sender.py:send():238] send: stats
2024-02-13 01:04:16,226 DEBUG   HandlerThread:10788 [handler.py:handle_request():130] handle_request: stop_status
2024-02-13 01:04:16,227 DEBUG   SenderThread:10788 [sender.py:send_request():252] send_request: stop_status
2024-02-13 01:04:21,180 INFO    Thread-12 :10788 [dir_watcher.py:_on_file_modified():230] file/dir modified: D:\jichuang\CNN\mydata\wandb\run-20240213_002618-1j1aaaj0\files\output.log
2024-02-13 01:04:26,341 ERROR   Thread-15 :10788 [internal_api.py:upload_file():1574] upload_file exception https://storage.googleapis.com/wandb-production.appspot.com/zhang-long/YOLOv8/1j1aaaj0/wandb-metadata.json?Expires=1707841619&GoogleAccessId=gorilla-files-url-signer-man%40wandb-production.iam.gserviceaccount.com&Signature=cZf8JvwvlyEan783%2FoIdBDuP%2FMRPKSJL8%2BJSgcHjEItD5k2%2FF7eKrUZ7lgys4kV2WsnuLKpQ5HnMsXpghu3%2FknwXChnrl1%2F0nA2B94diUHh2Uhfri%2BB5ySqP8gLS0rrstUyOyZStcDvpGbHoEOU39Bfe5R27RJ443lezMxVhCVVj9l2dEtnfHoyClDIBDQKJRW596k7G%2BOSXaA05gYm2S%2FFe9%2FXuFhKmtXBM9KC5LZy02%2FmmQolIV1%2F5KVe%2BbB7AuXJxrsuA%2FnvuWC4oj5wjPLIcueBkI5r6wmlTuRs4kmsq3UFS%2FEp1AzlXrAleSUkZeR41A8wIZML%2FdAYh4m8IwQ%3D%3D HTTPSConnectionPool(host='storage.googleapis.com', port=443): Max retries exceeded with url: /wandb-production.appspot.com/zhang-long/YOLOv8/1j1aaaj0/wandb-metadata.json?Expires=1707841619&GoogleAccessId=gorilla-files-url-signer-man%40wandb-production.iam.gserviceaccount.com&Signature=cZf8JvwvlyEan783%2FoIdBDuP%2FMRPKSJL8%2BJSgcHjEItD5k2%2FF7eKrUZ7lgys4kV2WsnuLKpQ5HnMsXpghu3%2FknwXChnrl1%2F0nA2B94diUHh2Uhfri%2BB5ySqP8gLS0rrstUyOyZStcDvpGbHoEOU39Bfe5R27RJ443lezMxVhCVVj9l2dEtnfHoyClDIBDQKJRW596k7G%2BOSXaA05gYm2S%2FFe9%2FXuFhKmtXBM9KC5LZy02%2FmmQolIV1%2F5KVe%2BbB7AuXJxrsuA%2FnvuWC4oj5wjPLIcueBkI5r6wmlTuRs4kmsq3UFS%2FEp1AzlXrAleSUkZeR41A8wIZML%2FdAYh4m8IwQ%3D%3D (Caused by NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x0000014CF549F700>: Failed to resolve 'storage.googleapis.com' ([Errno 11004] getaddrinfo failed)"))
2024-02-13 01:04:31,695 DEBUG   HandlerThread:10788 [handler.py:handle_request():130] handle_request: stop_status
2024-02-13 01:04:31,695 DEBUG   SenderThread:10788 [sender.py:send_request():252] send_request: stop_status
2024-02-13 01:04:47,146 DEBUG   HandlerThread:10788 [handler.py:handle_request():130] handle_request: stop_status
2024-02-13 01:04:47,146 DEBUG   SenderThread:10788 [sender.py:send_request():252] send_request: stop_status
2024-02-13 01:04:51,313 DEBUG   SenderThread:10788 [sender.py:send():238] send: stats
2024-02-13 01:04:56,806 INFO    Thread-12 :10788 [dir_watcher.py:_on_file_modified():230] file/dir modified: D:\jichuang\CNN\mydata\wandb\run-20240213_002618-1j1aaaj0\files\output.log
2024-02-13 01:05:02,639 DEBUG   HandlerThread:10788 [handler.py:handle_request():130] handle_request: stop_status
2024-02-13 01:05:02,640 DEBUG   SenderThread:10788 [sender.py:send_request():252] send_request: stop_status
2024-02-13 01:05:18,163 DEBUG   HandlerThread:10788 [handler.py:handle_request():130] handle_request: stop_status
2024-02-13 01:05:18,163 DEBUG   SenderThread:10788 [sender.py:send_request():252] send_request: stop_status
2024-02-13 01:05:26,864 DEBUG   SenderThread:10788 [sender.py:send():238] send: stats
2024-02-13 01:05:33,639 DEBUG   HandlerThread:10788 [handler.py:handle_request():130] handle_request: stop_status
2024-02-13 01:05:33,639 DEBUG   SenderThread:10788 [sender.py:send_request():252] send_request: stop_status
2024-02-13 01:05:35,546 INFO    Thread-12 :10788 [dir_watcher.py:_on_file_modified():230] file/dir modified: D:\jichuang\CNN\mydata\wandb\run-20240213_002618-1j1aaaj0\files\output.log
2024-02-13 01:05:49,870 DEBUG   HandlerThread:10788 [handler.py:handle_request():130] handle_request: stop_status
2024-02-13 01:05:49,871 DEBUG   SenderThread:10788 [sender.py:send_request():252] send_request: stop_status
2024-02-13 01:06:02,892 DEBUG   SenderThread:10788 [sender.py:send():238] send: stats
2024-02-13 01:06:05,321 DEBUG   HandlerThread:10788 [handler.py:handle_request():130] handle_request: stop_status
2024-02-13 01:06:05,322 DEBUG   SenderThread:10788 [sender.py:send_request():252] send_request: stop_status
2024-02-13 01:06:13,391 INFO    Thread-12 :10788 [dir_watcher.py:_on_file_modified():230] file/dir modified: D:\jichuang\CNN\mydata\wandb\run-20240213_002618-1j1aaaj0\files\output.log
2024-02-13 01:06:20,817 DEBUG   HandlerThread:10788 [handler.py:handle_request():130] handle_request: stop_status
2024-02-13 01:06:20,817 DEBUG   SenderThread:10788 [sender.py:send_request():252] send_request: stop_status
2024-02-13 01:06:36,283 DEBUG   HandlerThread:10788 [handler.py:handle_request():130] handle_request: stop_status
2024-02-13 01:06:36,284 DEBUG   SenderThread:10788 [sender.py:send_request():252] send_request: stop_status
2024-02-13 01:06:38,463 DEBUG   SenderThread:10788 [sender.py:send():238] send: stats
2024-02-13 01:06:51,833 DEBUG   HandlerThread:10788 [handler.py:handle_request():130] handle_request: stop_status
2024-02-13 01:06:51,834 DEBUG   SenderThread:10788 [sender.py:send_request():252] send_request: stop_status
2024-02-13 01:06:52,126 INFO    Thread-12 :10788 [dir_watcher.py:_on_file_modified():230] file/dir modified: D:\jichuang\CNN\mydata\wandb\run-20240213_002618-1j1aaaj0\files\output.log
2024-02-13 01:07:07,359 DEBUG   HandlerThread:10788 [handler.py:handle_request():130] handle_request: stop_status
2024-02-13 01:07:07,359 DEBUG   SenderThread:10788 [sender.py:send_request():252] send_request: stop_status
2024-02-13 01:07:13,722 DEBUG   SenderThread:10788 [sender.py:send():238] send: stats
2024-02-13 01:07:22,885 DEBUG   HandlerThread:10788 [handler.py:handle_request():130] handle_request: stop_status
2024-02-13 01:07:22,886 DEBUG   SenderThread:10788 [sender.py:send_request():252] send_request: stop_status
2024-02-13 01:07:27,737 INFO    Thread-12 :10788 [dir_watcher.py:_on_file_modified():230] file/dir modified: D:\jichuang\CNN\mydata\wandb\run-20240213_002618-1j1aaaj0\files\output.log
2024-02-13 01:07:38,384 DEBUG   HandlerThread:10788 [handler.py:handle_request():130] handle_request: stop_status
2024-02-13 01:07:38,384 DEBUG   SenderThread:10788 [sender.py:send_request():252] send_request: stop_status
2024-02-13 01:07:49,485 DEBUG   SenderThread:10788 [sender.py:send():238] send: stats
2024-02-13 01:07:53,838 DEBUG   HandlerThread:10788 [handler.py:handle_request():130] handle_request: stop_status
2024-02-13 01:07:53,839 DEBUG   SenderThread:10788 [sender.py:send_request():252] send_request: stop_status
2024-02-13 01:08:02,454 INFO    Thread-12 :10788 [dir_watcher.py:_on_file_modified():230] file/dir modified: D:\jichuang\CNN\mydata\wandb\run-20240213_002618-1j1aaaj0\files\output.log
2024-02-13 01:08:09,312 DEBUG   HandlerThread:10788 [handler.py:handle_request():130] handle_request: stop_status
2024-02-13 01:08:09,313 DEBUG   SenderThread:10788 [sender.py:send_request():252] send_request: stop_status
2024-02-13 01:08:24,791 DEBUG   HandlerThread:10788 [handler.py:handle_request():130] handle_request: stop_status
2024-02-13 01:08:24,791 DEBUG   SenderThread:10788 [sender.py:send_request():252] send_request: stop_status
2024-02-13 01:08:25,300 DEBUG   SenderThread:10788 [sender.py:send():238] send: stats
2024-02-13 01:08:40,145 INFO    Thread-12 :10788 [dir_watcher.py:_on_file_modified():230] file/dir modified: D:\jichuang\CNN\mydata\wandb\run-20240213_002618-1j1aaaj0\files\output.log
2024-02-13 01:08:40,318 DEBUG   HandlerThread:10788 [handler.py:handle_request():130] handle_request: stop_status
2024-02-13 01:08:40,319 DEBUG   SenderThread:10788 [sender.py:send_request():252] send_request: stop_status
2024-02-13 01:08:55,817 DEBUG   HandlerThread:10788 [handler.py:handle_request():130] handle_request: stop_status
2024-02-13 01:08:55,818 DEBUG   SenderThread:10788 [sender.py:send_request():252] send_request: stop_status
2024-02-13 01:09:00,264 DEBUG   SenderThread:10788 [sender.py:send():238] send: stats
2024-02-13 01:09:11,404 DEBUG   HandlerThread:10788 [handler.py:handle_request():130] handle_request: stop_status
2024-02-13 01:09:11,404 DEBUG   SenderThread:10788 [sender.py:send_request():252] send_request: stop_status
2024-02-13 01:09:14,815 INFO    Thread-12 :10788 [dir_watcher.py:_on_file_modified():230] file/dir modified: D:\jichuang\CNN\mydata\wandb\run-20240213_002618-1j1aaaj0\files\output.log
2024-02-13 01:09:26,843 DEBUG   HandlerThread:10788 [handler.py:handle_request():130] handle_request: stop_status
2024-02-13 01:09:26,843 DEBUG   SenderThread:10788 [sender.py:send_request():252] send_request: stop_status
2024-02-13 01:09:35,973 DEBUG   SenderThread:10788 [sender.py:send():238] send: stats
2024-02-13 01:09:42,315 DEBUG   HandlerThread:10788 [handler.py:handle_request():130] handle_request: stop_status
2024-02-13 01:09:42,315 DEBUG   SenderThread:10788 [sender.py:send_request():252] send_request: stop_status
2024-02-13 01:09:51,559 INFO    Thread-12 :10788 [dir_watcher.py:_on_file_modified():230] file/dir modified: D:\jichuang\CNN\mydata\wandb\run-20240213_002618-1j1aaaj0\files\output.log
2024-02-13 01:09:57,844 DEBUG   HandlerThread:10788 [handler.py:handle_request():130] handle_request: stop_status
2024-02-13 01:09:57,844 DEBUG   SenderThread:10788 [sender.py:send_request():252] send_request: stop_status
2024-02-13 01:10:05,984 ERROR   Thread-15 :10788 [internal_api.py:upload_file():1574] upload_file exception https://storage.googleapis.com/wandb-production.appspot.com/zhang-long/YOLOv8/1j1aaaj0/wandb-metadata.json?Expires=1707841619&GoogleAccessId=gorilla-files-url-signer-man%40wandb-production.iam.gserviceaccount.com&Signature=cZf8JvwvlyEan783%2FoIdBDuP%2FMRPKSJL8%2BJSgcHjEItD5k2%2FF7eKrUZ7lgys4kV2WsnuLKpQ5HnMsXpghu3%2FknwXChnrl1%2F0nA2B94diUHh2Uhfri%2BB5ySqP8gLS0rrstUyOyZStcDvpGbHoEOU39Bfe5R27RJ443lezMxVhCVVj9l2dEtnfHoyClDIBDQKJRW596k7G%2BOSXaA05gYm2S%2FFe9%2FXuFhKmtXBM9KC5LZy02%2FmmQolIV1%2F5KVe%2BbB7AuXJxrsuA%2FnvuWC4oj5wjPLIcueBkI5r6wmlTuRs4kmsq3UFS%2FEp1AzlXrAleSUkZeR41A8wIZML%2FdAYh4m8IwQ%3D%3D HTTPSConnectionPool(host='storage.googleapis.com', port=443): Max retries exceeded with url: /wandb-production.appspot.com/zhang-long/YOLOv8/1j1aaaj0/wandb-metadata.json?Expires=1707841619&GoogleAccessId=gorilla-files-url-signer-man%40wandb-production.iam.gserviceaccount.com&Signature=cZf8JvwvlyEan783%2FoIdBDuP%2FMRPKSJL8%2BJSgcHjEItD5k2%2FF7eKrUZ7lgys4kV2WsnuLKpQ5HnMsXpghu3%2FknwXChnrl1%2F0nA2B94diUHh2Uhfri%2BB5ySqP8gLS0rrstUyOyZStcDvpGbHoEOU39Bfe5R27RJ443lezMxVhCVVj9l2dEtnfHoyClDIBDQKJRW596k7G%2BOSXaA05gYm2S%2FFe9%2FXuFhKmtXBM9KC5LZy02%2FmmQolIV1%2F5KVe%2BbB7AuXJxrsuA%2FnvuWC4oj5wjPLIcueBkI5r6wmlTuRs4kmsq3UFS%2FEp1AzlXrAleSUkZeR41A8wIZML%2FdAYh4m8IwQ%3D%3D (Caused by NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x0000014CF54C6E80>: Failed to resolve 'storage.googleapis.com' ([Errno 11004] getaddrinfo failed)"))
2024-02-13 01:10:11,258 DEBUG   SenderThread:10788 [sender.py:send():238] send: stats
2024-02-13 01:10:13,333 DEBUG   HandlerThread:10788 [handler.py:handle_request():130] handle_request: stop_status
2024-02-13 01:10:13,334 DEBUG   SenderThread:10788 [sender.py:send_request():252] send_request: stop_status
2024-02-13 01:10:27,306 INFO    Thread-12 :10788 [dir_watcher.py:_on_file_modified():230] file/dir modified: D:\jichuang\CNN\mydata\wandb\run-20240213_002618-1j1aaaj0\files\output.log
2024-02-13 01:10:28,809 DEBUG   HandlerThread:10788 [handler.py:handle_request():130] handle_request: stop_status
2024-02-13 01:10:28,810 DEBUG   SenderThread:10788 [sender.py:send_request():252] send_request: stop_status
2024-02-13 01:10:44,276 DEBUG   HandlerThread:10788 [handler.py:handle_request():130] handle_request: stop_status
2024-02-13 01:10:44,277 DEBUG   SenderThread:10788 [sender.py:send_request():252] send_request: stop_status
2024-02-13 01:10:47,152 DEBUG   SenderThread:10788 [sender.py:send():238] send: stats
2024-02-13 01:10:59,774 DEBUG   HandlerThread:10788 [handler.py:handle_request():130] handle_request: stop_status
2024-02-13 01:10:59,774 DEBUG   SenderThread:10788 [sender.py:send_request():252] send_request: stop_status
2024-02-13 01:11:10,177 INFO    Thread-12 :10788 [dir_watcher.py:_on_file_modified():230] file/dir modified: D:\jichuang\CNN\mydata\wandb\run-20240213_002618-1j1aaaj0\files\output.log
2024-02-13 01:11:15,281 DEBUG   HandlerThread:10788 [handler.py:handle_request():130] handle_request: stop_status
2024-02-13 01:11:15,282 DEBUG   SenderThread:10788 [sender.py:send_request():252] send_request: stop_status
2024-02-13 01:11:23,246 DEBUG   SenderThread:10788 [sender.py:send():238] send: stats
2024-02-13 01:11:30,750 DEBUG   HandlerThread:10788 [handler.py:handle_request():130] handle_request: stop_status
2024-02-13 01:11:30,751 DEBUG   SenderThread:10788 [sender.py:send_request():252] send_request: stop_status
2024-02-13 01:11:46,283 DEBUG   HandlerThread:10788 [handler.py:handle_request():130] handle_request: stop_status
2024-02-13 01:11:46,284 DEBUG   SenderThread:10788 [sender.py:send_request():252] send_request: stop_status
2024-02-13 01:11:47,924 INFO    Thread-12 :10788 [dir_watcher.py:_on_file_modified():230] file/dir modified: D:\jichuang\CNN\mydata\wandb\run-20240213_002618-1j1aaaj0\files\output.log
2024-02-13 01:11:58,826 DEBUG   SenderThread:10788 [sender.py:send():238] send: stats
2024-02-13 01:12:01,788 DEBUG   HandlerThread:10788 [handler.py:handle_request():130] handle_request: stop_status
2024-02-13 01:12:01,789 DEBUG   SenderThread:10788 [sender.py:send_request():252] send_request: stop_status
2024-02-13 01:12:19,937 DEBUG   HandlerThread:10788 [handler.py:handle_request():130] handle_request: stop_status
2024-02-13 01:12:19,938 DEBUG   SenderThread:10788 [sender.py:send_request():252] send_request: stop_status
2024-02-13 01:12:24,614 INFO    Thread-12 :10788 [dir_watcher.py:_on_file_modified():230] file/dir modified: D:\jichuang\CNN\mydata\wandb\run-20240213_002618-1j1aaaj0\files\output.log
2024-02-13 01:12:34,609 DEBUG   SenderThread:10788 [sender.py:send():238] send: stats
2024-02-13 01:12:35,402 DEBUG   HandlerThread:10788 [handler.py:handle_request():130] handle_request: stop_status
2024-02-13 01:12:35,402 DEBUG   SenderThread:10788 [sender.py:send_request():252] send_request: stop_status
2024-02-13 01:12:50,875 DEBUG   HandlerThread:10788 [handler.py:handle_request():130] handle_request: stop_status
2024-02-13 01:12:50,876 DEBUG   SenderThread:10788 [sender.py:send_request():252] send_request: stop_status
2024-02-13 01:12:59,231 INFO    Thread-12 :10788 [dir_watcher.py:_on_file_modified():230] file/dir modified: D:\jichuang\CNN\mydata\wandb\run-20240213_002618-1j1aaaj0\files\output.log
2024-02-13 01:13:06,383 DEBUG   HandlerThread:10788 [handler.py:handle_request():130] handle_request: stop_status
2024-02-13 01:13:06,384 DEBUG   SenderThread:10788 [sender.py:send_request():252] send_request: stop_status
2024-02-13 01:13:09,664 DEBUG   SenderThread:10788 [sender.py:send():238] send: stats
2024-02-13 01:13:21,914 DEBUG   HandlerThread:10788 [handler.py:handle_request():130] handle_request: stop_status
2024-02-13 01:13:21,915 DEBUG   SenderThread:10788 [sender.py:send_request():252] send_request: stop_status
2024-02-13 01:13:36,988 INFO    Thread-12 :10788 [dir_watcher.py:_on_file_modified():230] file/dir modified: D:\jichuang\CNN\mydata\wandb\run-20240213_002618-1j1aaaj0\files\output.log
2024-02-13 01:13:37,348 DEBUG   HandlerThread:10788 [handler.py:handle_request():130] handle_request: stop_status
2024-02-13 01:13:37,348 DEBUG   SenderThread:10788 [sender.py:send_request():252] send_request: stop_status
2024-02-13 01:13:45,237 DEBUG   SenderThread:10788 [sender.py:send():238] send: stats
2024-02-13 01:13:52,825 DEBUG   HandlerThread:10788 [handler.py:handle_request():130] handle_request: stop_status
2024-02-13 01:13:52,825 DEBUG   SenderThread:10788 [sender.py:send_request():252] send_request: stop_status
2024-02-13 01:14:08,326 DEBUG   HandlerThread:10788 [handler.py:handle_request():130] handle_request: stop_status
2024-02-13 01:14:08,326 DEBUG   SenderThread:10788 [sender.py:send_request():252] send_request: stop_status
2024-02-13 01:14:09,640 INFO    Thread-12 :10788 [dir_watcher.py:_on_file_modified():230] file/dir modified: D:\jichuang\CNN\mydata\wandb\run-20240213_002618-1j1aaaj0\files\output.log
2024-02-13 01:14:20,808 DEBUG   SenderThread:10788 [sender.py:send():238] send: stats
2024-02-13 01:14:23,782 DEBUG   HandlerThread:10788 [handler.py:handle_request():130] handle_request: stop_status
2024-02-13 01:14:23,782 DEBUG   SenderThread:10788 [sender.py:send_request():252] send_request: stop_status
2024-02-13 01:14:39,282 DEBUG   HandlerThread:10788 [handler.py:handle_request():130] handle_request: stop_status
2024-02-13 01:14:39,282 DEBUG   SenderThread:10788 [sender.py:send_request():252] send_request: stop_status
2024-02-13 01:14:48,351 INFO    Thread-12 :10788 [dir_watcher.py:_on_file_modified():230] file/dir modified: D:\jichuang\CNN\mydata\wandb\run-20240213_002618-1j1aaaj0\files\output.log
2024-02-13 01:14:54,774 DEBUG   HandlerThread:10788 [handler.py:handle_request():130] handle_request: stop_status
2024-02-13 01:14:54,774 DEBUG   SenderThread:10788 [sender.py:send_request():252] send_request: stop_status
2024-02-13 01:14:56,079 DEBUG   SenderThread:10788 [sender.py:send():238] send: stats
2024-02-13 01:15:10,208 DEBUG   HandlerThread:10788 [handler.py:handle_request():130] handle_request: stop_status
2024-02-13 01:15:10,209 DEBUG   SenderThread:10788 [sender.py:send_request():252] send_request: stop_status
2024-02-13 01:15:21,956 INFO    Thread-12 :10788 [dir_watcher.py:_on_file_modified():230] file/dir modified: D:\jichuang\CNN\mydata\wandb\run-20240213_002618-1j1aaaj0\files\output.log
2024-02-13 01:15:25,690 DEBUG   HandlerThread:10788 [handler.py:handle_request():130] handle_request: stop_status
2024-02-13 01:15:25,690 DEBUG   SenderThread:10788 [sender.py:send_request():252] send_request: stop_status
2024-02-13 01:15:31,591 DEBUG   SenderThread:10788 [sender.py:send():238] send: stats
2024-02-13 01:15:41,221 DEBUG   HandlerThread:10788 [handler.py:handle_request():130] handle_request: stop_status
2024-02-13 01:15:41,221 DEBUG   SenderThread:10788 [sender.py:send_request():252] send_request: stop_status
2024-02-13 01:15:56,628 DEBUG   HandlerThread:10788 [handler.py:handle_request():130] handle_request: stop_status
2024-02-13 01:15:56,629 DEBUG   SenderThread:10788 [sender.py:send_request():252] send_request: stop_status
2024-02-13 01:16:02,657 INFO    Thread-12 :10788 [dir_watcher.py:_on_file_modified():230] file/dir modified: D:\jichuang\CNN\mydata\wandb\run-20240213_002618-1j1aaaj0\files\output.log
2024-02-13 01:16:07,016 DEBUG   SenderThread:10788 [sender.py:send():238] send: stats
2024-02-13 01:16:12,075 DEBUG   HandlerThread:10788 [handler.py:handle_request():130] handle_request: stop_status
2024-02-13 01:16:12,075 DEBUG   SenderThread:10788 [sender.py:send_request():252] send_request: stop_status
2024-02-13 01:16:12,296 ERROR   Thread-15 :10788 [internal_api.py:upload_file():1574] upload_file exception https://storage.googleapis.com/wandb-production.appspot.com/zhang-long/YOLOv8/1j1aaaj0/wandb-metadata.json?Expires=1707841619&GoogleAccessId=gorilla-files-url-signer-man%40wandb-production.iam.gserviceaccount.com&Signature=cZf8JvwvlyEan783%2FoIdBDuP%2FMRPKSJL8%2BJSgcHjEItD5k2%2FF7eKrUZ7lgys4kV2WsnuLKpQ5HnMsXpghu3%2FknwXChnrl1%2F0nA2B94diUHh2Uhfri%2BB5ySqP8gLS0rrstUyOyZStcDvpGbHoEOU39Bfe5R27RJ443lezMxVhCVVj9l2dEtnfHoyClDIBDQKJRW596k7G%2BOSXaA05gYm2S%2FFe9%2FXuFhKmtXBM9KC5LZy02%2FmmQolIV1%2F5KVe%2BbB7AuXJxrsuA%2FnvuWC4oj5wjPLIcueBkI5r6wmlTuRs4kmsq3UFS%2FEp1AzlXrAleSUkZeR41A8wIZML%2FdAYh4m8IwQ%3D%3D HTTPSConnectionPool(host='storage.googleapis.com', port=443): Max retries exceeded with url: /wandb-production.appspot.com/zhang-long/YOLOv8/1j1aaaj0/wandb-metadata.json?Expires=1707841619&GoogleAccessId=gorilla-files-url-signer-man%40wandb-production.iam.gserviceaccount.com&Signature=cZf8JvwvlyEan783%2FoIdBDuP%2FMRPKSJL8%2BJSgcHjEItD5k2%2FF7eKrUZ7lgys4kV2WsnuLKpQ5HnMsXpghu3%2FknwXChnrl1%2F0nA2B94diUHh2Uhfri%2BB5ySqP8gLS0rrstUyOyZStcDvpGbHoEOU39Bfe5R27RJ443lezMxVhCVVj9l2dEtnfHoyClDIBDQKJRW596k7G%2BOSXaA05gYm2S%2FFe9%2FXuFhKmtXBM9KC5LZy02%2FmmQolIV1%2F5KVe%2BbB7AuXJxrsuA%2FnvuWC4oj5wjPLIcueBkI5r6wmlTuRs4kmsq3UFS%2FEp1AzlXrAleSUkZeR41A8wIZML%2FdAYh4m8IwQ%3D%3D (Caused by NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x0000014CF5591610>: Failed to resolve 'storage.googleapis.com' ([Errno 11004] getaddrinfo failed)"))
2024-02-13 01:16:27,639 DEBUG   HandlerThread:10788 [handler.py:handle_request():130] handle_request: stop_status
2024-02-13 01:16:27,639 DEBUG   SenderThread:10788 [sender.py:send_request():252] send_request: stop_status
2024-02-13 01:16:31,174 INFO    Thread-12 :10788 [dir_watcher.py:_on_file_modified():230] file/dir modified: D:\jichuang\CNN\mydata\wandb\run-20240213_002618-1j1aaaj0\files\output.log
2024-02-13 01:16:43,061 DEBUG   SenderThread:10788 [sender.py:send():238] send: stats
2024-02-13 01:16:43,091 DEBUG   HandlerThread:10788 [handler.py:handle_request():130] handle_request: stop_status
2024-02-13 01:16:43,092 DEBUG   SenderThread:10788 [sender.py:send_request():252] send_request: stop_status
2024-02-13 01:16:52,628 INFO    Thread-12 :10788 [dir_watcher.py:_on_file_modified():230] file/dir modified: D:\jichuang\CNN\mydata\wandb\run-20240213_002618-1j1aaaj0\files\output.log
2024-02-13 01:16:58,497 DEBUG   HandlerThread:10788 [handler.py:handle_request():130] handle_request: stop_status
2024-02-13 01:16:58,498 DEBUG   SenderThread:10788 [sender.py:send_request():252] send_request: stop_status
2024-02-13 01:17:14,058 DEBUG   HandlerThread:10788 [handler.py:handle_request():130] handle_request: stop_status
2024-02-13 01:17:14,059 DEBUG   SenderThread:10788 [sender.py:send_request():252] send_request: stop_status
2024-02-13 01:17:15,092 INFO    Thread-12 :10788 [dir_watcher.py:_on_file_modified():230] file/dir modified: D:\jichuang\CNN\mydata\wandb\run-20240213_002618-1j1aaaj0\files\output.log
2024-02-13 01:17:19,135 DEBUG   SenderThread:10788 [sender.py:send():238] send: stats
2024-02-13 01:17:29,573 DEBUG   HandlerThread:10788 [handler.py:handle_request():130] handle_request: stop_status
2024-02-13 01:17:29,573 DEBUG   SenderThread:10788 [sender.py:send_request():252] send_request: stop_status
2024-02-13 01:17:41,633 INFO    Thread-12 :10788 [dir_watcher.py:_on_file_modified():230] file/dir modified: D:\jichuang\CNN\mydata\wandb\run-20240213_002618-1j1aaaj0\files\output.log
2024-02-13 01:17:45,028 DEBUG   HandlerThread:10788 [handler.py:handle_request():130] handle_request: stop_status
2024-02-13 01:17:45,029 DEBUG   SenderThread:10788 [sender.py:send_request():252] send_request: stop_status
2024-02-13 01:17:55,443 DEBUG   SenderThread:10788 [sender.py:send():238] send: stats
2024-02-13 01:18:00,497 DEBUG   HandlerThread:10788 [handler.py:handle_request():130] handle_request: stop_status
2024-02-13 01:18:00,498 DEBUG   SenderThread:10788 [sender.py:send_request():252] send_request: stop_status
2024-02-13 01:18:04,010 INFO    Thread-12 :10788 [dir_watcher.py:_on_file_modified():230] file/dir modified: D:\jichuang\CNN\mydata\wandb\run-20240213_002618-1j1aaaj0\files\output.log
2024-02-13 01:18:19,784 DEBUG   HandlerThread:10788 [handler.py:handle_request():130] handle_request: stop_status
2024-02-13 01:18:19,793 DEBUG   SenderThread:10788 [sender.py:send_request():252] send_request: stop_status
2024-02-13 01:18:28,429 INFO    Thread-12 :10788 [dir_watcher.py:_on_file_modified():230] file/dir modified: D:\jichuang\CNN\mydata\wandb\run-20240213_002618-1j1aaaj0\files\output.log
2024-02-13 01:18:32,035 DEBUG   SenderThread:10788 [sender.py:send():238] send: stats
2024-02-13 01:18:35,317 DEBUG   HandlerThread:10788 [handler.py:handle_request():130] handle_request: stop_status
2024-02-13 01:18:35,317 DEBUG   SenderThread:10788 [sender.py:send_request():252] send_request: stop_status
2024-02-13 01:18:50,801 DEBUG   HandlerThread:10788 [handler.py:handle_request():130] handle_request: stop_status
2024-02-13 01:18:50,801 DEBUG   SenderThread:10788 [sender.py:send_request():252] send_request: stop_status
2024-02-13 01:18:51,814 INFO    Thread-12 :10788 [dir_watcher.py:_on_file_modified():230] file/dir modified: D:\jichuang\CNN\mydata\wandb\run-20240213_002618-1j1aaaj0\files\output.log
2024-02-13 01:19:06,396 DEBUG   HandlerThread:10788 [handler.py:handle_request():130] handle_request: stop_status
2024-02-13 01:19:06,396 DEBUG   SenderThread:10788 [sender.py:send_request():252] send_request: stop_status
2024-02-13 01:19:10,489 DEBUG   SenderThread:10788 [sender.py:send():238] send: stats
2024-02-13 01:19:21,906 DEBUG   HandlerThread:10788 [handler.py:handle_request():130] handle_request: stop_status
2024-02-13 01:19:21,906 DEBUG   SenderThread:10788 [sender.py:send_request():252] send_request: stop_status
2024-02-13 01:19:24,439 INFO    Thread-12 :10788 [dir_watcher.py:_on_file_modified():230] file/dir modified: D:\jichuang\CNN\mydata\wandb\run-20240213_002618-1j1aaaj0\files\output.log
2024-02-13 01:19:37,359 DEBUG   HandlerThread:10788 [handler.py:handle_request():130] handle_request: stop_status
2024-02-13 01:19:37,359 DEBUG   SenderThread:10788 [sender.py:send_request():252] send_request: stop_status
2024-02-13 01:19:51,027 DEBUG   SenderThread:10788 [sender.py:send():238] send: stats
2024-02-13 01:19:52,862 DEBUG   HandlerThread:10788 [handler.py:handle_request():130] handle_request: stop_status
2024-02-13 01:19:52,863 DEBUG   SenderThread:10788 [sender.py:send_request():252] send_request: stop_status
2024-02-13 01:19:53,187 INFO    Thread-12 :10788 [dir_watcher.py:_on_file_modified():230] file/dir modified: D:\jichuang\CNN\mydata\wandb\run-20240213_002618-1j1aaaj0\files\output.log
2024-02-13 01:20:02,327 INFO    Thread-12 :10788 [dir_watcher.py:_on_file_modified():230] file/dir modified: D:\jichuang\CNN\mydata\wandb\run-20240213_002618-1j1aaaj0\files\output.log
2024-02-13 01:20:03,345 INFO    Thread-12 :10788 [dir_watcher.py:_on_file_modified():230] file/dir modified: D:\jichuang\CNN\mydata\wandb\run-20240213_002618-1j1aaaj0\files\output.log
2024-02-13 01:20:04,350 INFO    Thread-12 :10788 [dir_watcher.py:_on_file_modified():230] file/dir modified: D:\jichuang\CNN\mydata\wandb\run-20240213_002618-1j1aaaj0\files\output.log
2024-02-13 01:20:05,386 INFO    Thread-12 :10788 [dir_watcher.py:_on_file_modified():230] file/dir modified: D:\jichuang\CNN\mydata\wandb\run-20240213_002618-1j1aaaj0\files\output.log
2024-02-13 01:20:07,434 INFO    Thread-12 :10788 [dir_watcher.py:_on_file_modified():230] file/dir modified: D:\jichuang\CNN\mydata\wandb\run-20240213_002618-1j1aaaj0\files\output.log
2024-02-13 01:20:08,412 DEBUG   HandlerThread:10788 [handler.py:handle_request():130] handle_request: stop_status
2024-02-13 01:20:08,413 DEBUG   SenderThread:10788 [sender.py:send_request():252] send_request: stop_status
2024-02-13 01:20:23,970 DEBUG   HandlerThread:10788 [handler.py:handle_request():130] handle_request: stop_status
2024-02-13 01:20:23,970 DEBUG   SenderThread:10788 [sender.py:send_request():252] send_request: stop_status
2024-02-13 01:20:27,883 DEBUG   SenderThread:10788 [sender.py:send():238] send: stats
2024-02-13 01:20:39,615 DEBUG   HandlerThread:10788 [handler.py:handle_request():130] handle_request: stop_status
2024-02-13 01:20:39,615 DEBUG   SenderThread:10788 [sender.py:send_request():252] send_request: stop_status
2024-02-13 01:20:53,794 INFO    Thread-12 :10788 [dir_watcher.py:_on_file_modified():230] file/dir modified: D:\jichuang\CNN\mydata\wandb\run-20240213_002618-1j1aaaj0\files\output.log
2024-02-13 01:20:55,135 DEBUG   HandlerThread:10788 [handler.py:handle_request():130] handle_request: stop_status
2024-02-13 01:20:55,136 DEBUG   SenderThread:10788 [sender.py:send_request():252] send_request: stop_status
2024-02-13 01:21:05,085 DEBUG   SenderThread:10788 [sender.py:send():238] send: stats
2024-02-13 01:21:10,526 DEBUG   HandlerThread:10788 [handler.py:handle_request():130] handle_request: stop_status
2024-02-13 01:21:10,527 DEBUG   SenderThread:10788 [sender.py:send_request():252] send_request: stop_status
2024-02-13 01:21:25,992 DEBUG   HandlerThread:10788 [handler.py:handle_request():130] handle_request: stop_status
2024-02-13 01:21:25,992 DEBUG   SenderThread:10788 [sender.py:send_request():252] send_request: stop_status
2024-02-13 01:21:39,912 INFO    Thread-12 :10788 [dir_watcher.py:_on_file_modified():230] file/dir modified: D:\jichuang\CNN\mydata\wandb\run-20240213_002618-1j1aaaj0\files\output.log
2024-02-13 01:21:41,472 DEBUG   HandlerThread:10788 [handler.py:handle_request():130] handle_request: stop_status
2024-02-13 01:21:41,472 DEBUG   SenderThread:10788 [sender.py:send_request():252] send_request: stop_status
2024-02-13 01:21:42,019 DEBUG   SenderThread:10788 [sender.py:send():238] send: stats
2024-02-13 01:21:45,845 ERROR   Thread-15 :10788 [internal_api.py:upload_file():1574] upload_file exception https://storage.googleapis.com/wandb-production.appspot.com/zhang-long/YOLOv8/1j1aaaj0/wandb-metadata.json?Expires=1707841619&GoogleAccessId=gorilla-files-url-signer-man%40wandb-production.iam.gserviceaccount.com&Signature=cZf8JvwvlyEan783%2FoIdBDuP%2FMRPKSJL8%2BJSgcHjEItD5k2%2FF7eKrUZ7lgys4kV2WsnuLKpQ5HnMsXpghu3%2FknwXChnrl1%2F0nA2B94diUHh2Uhfri%2BB5ySqP8gLS0rrstUyOyZStcDvpGbHoEOU39Bfe5R27RJ443lezMxVhCVVj9l2dEtnfHoyClDIBDQKJRW596k7G%2BOSXaA05gYm2S%2FFe9%2FXuFhKmtXBM9KC5LZy02%2FmmQolIV1%2F5KVe%2BbB7AuXJxrsuA%2FnvuWC4oj5wjPLIcueBkI5r6wmlTuRs4kmsq3UFS%2FEp1AzlXrAleSUkZeR41A8wIZML%2FdAYh4m8IwQ%3D%3D HTTPSConnectionPool(host='storage.googleapis.com', port=443): Max retries exceeded with url: /wandb-production.appspot.com/zhang-long/YOLOv8/1j1aaaj0/wandb-metadata.json?Expires=1707841619&GoogleAccessId=gorilla-files-url-signer-man%40wandb-production.iam.gserviceaccount.com&Signature=cZf8JvwvlyEan783%2FoIdBDuP%2FMRPKSJL8%2BJSgcHjEItD5k2%2FF7eKrUZ7lgys4kV2WsnuLKpQ5HnMsXpghu3%2FknwXChnrl1%2F0nA2B94diUHh2Uhfri%2BB5ySqP8gLS0rrstUyOyZStcDvpGbHoEOU39Bfe5R27RJ443lezMxVhCVVj9l2dEtnfHoyClDIBDQKJRW596k7G%2BOSXaA05gYm2S%2FFe9%2FXuFhKmtXBM9KC5LZy02%2FmmQolIV1%2F5KVe%2BbB7AuXJxrsuA%2FnvuWC4oj5wjPLIcueBkI5r6wmlTuRs4kmsq3UFS%2FEp1AzlXrAleSUkZeR41A8wIZML%2FdAYh4m8IwQ%3D%3D (Caused by NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x0000014CF54BDDF0>: Failed to resolve 'storage.googleapis.com' ([Errno 11004] getaddrinfo failed)"))
2024-02-13 01:21:57,047 DEBUG   HandlerThread:10788 [handler.py:handle_request():130] handle_request: stop_status
2024-02-13 01:21:57,048 DEBUG   SenderThread:10788 [sender.py:send_request():252] send_request: stop_status
2024-02-13 01:22:12,551 DEBUG   HandlerThread:10788 [handler.py:handle_request():130] handle_request: stop_status
2024-02-13 01:22:12,551 DEBUG   SenderThread:10788 [sender.py:send_request():252] send_request: stop_status
2024-02-13 01:22:14,538 INFO    Thread-12 :10788 [dir_watcher.py:_on_file_modified():230] file/dir modified: D:\jichuang\CNN\mydata\wandb\run-20240213_002618-1j1aaaj0\files\output.log
2024-02-13 01:22:17,310 DEBUG   SenderThread:10788 [sender.py:send():238] send: stats
2024-02-13 01:22:27,985 DEBUG   HandlerThread:10788 [handler.py:handle_request():130] handle_request: stop_status
2024-02-13 01:22:27,985 DEBUG   SenderThread:10788 [sender.py:send_request():252] send_request: stop_status
2024-02-13 01:22:35,561 WARNING MainThread:10788 [internal.py:wandb_internal():146] Internal process interrupt: 1
2024-02-13 01:22:36,012 WARNING MainThread:10788 [internal.py:wandb_internal():146] Internal process interrupt: 2
2024-02-13 01:22:36,012 ERROR   MainThread:10788 [internal.py:wandb_internal():149] Internal process interrupted.
2024-02-13 01:22:36,509 INFO    HandlerThread:10788 [handler.py:finish():731] shutting down handler
2024-02-13 01:22:36,522 INFO    SenderThread:10788 [sender.py:finish():1091] shutting down sender
2024-02-13 01:22:36,523 INFO    SenderThread:10788 [dir_watcher.py:finish():283] shutting down directory watcher
2024-02-13 01:22:36,726 INFO    WriterThread:10788 [datastore.py:close():281] close: D:\jichuang\CNN\mydata\wandb\run-20240213_002618-1j1aaaj0\run-1j1aaaj0.wandb
2024-02-13 01:22:36,987 INFO    SenderThread:10788 [dir_watcher.py:finish():313] scan: D:\jichuang\CNN\mydata\wandb\run-20240213_002618-1j1aaaj0\files
2024-02-13 01:22:36,988 INFO    SenderThread:10788 [dir_watcher.py:finish():327] scan save: D:\jichuang\CNN\mydata\wandb\run-20240213_002618-1j1aaaj0\files\conda-environment.yaml conda-environment.yaml
2024-02-13 01:22:36,989 INFO    SenderThread:10788 [dir_watcher.py:finish():327] scan save: D:\jichuang\CNN\mydata\wandb\run-20240213_002618-1j1aaaj0\files\config.yaml config.yaml
2024-02-13 01:22:36,990 INFO    SenderThread:10788 [dir_watcher.py:finish():327] scan save: D:\jichuang\CNN\mydata\wandb\run-20240213_002618-1j1aaaj0\files\output.log output.log
2024-02-13 01:22:36,993 INFO    SenderThread:10788 [dir_watcher.py:finish():327] scan save: D:\jichuang\CNN\mydata\wandb\run-20240213_002618-1j1aaaj0\files\requirements.txt requirements.txt
2024-02-13 01:22:36,995 INFO    SenderThread:10788 [dir_watcher.py:finish():327] scan save: D:\jichuang\CNN\mydata\wandb\run-20240213_002618-1j1aaaj0\files\wandb-metadata.json wandb-metadata.json
2024-02-13 01:22:36,995 INFO    SenderThread:10788 [dir_watcher.py:finish():327] scan save: D:\jichuang\CNN\mydata\wandb\run-20240213_002618-1j1aaaj0\files\wandb-summary.json wandb-summary.json
2024-02-13 01:22:36,996 INFO    SenderThread:10788 [file_pusher.py:finish():177] shutting down file pusher
2024-02-13 01:22:36,997 INFO    SenderThread:10788 [file_pusher.py:join():182] waiting for file pusher
2024-02-13 01:22:37,631 ERROR   Thread-16 :10788 [internal_api.py:upload_file():1574] upload_file exception https://storage.googleapis.com/wandb-production.appspot.com/zhang-long/YOLOv8/1j1aaaj0/config.yaml?Expires=1707844957&GoogleAccessId=gorilla-files-url-signer-man%40wandb-production.iam.gserviceaccount.com&Signature=ovc2ER9z3SR8biOK8sTfddSwfWBFIGW6fvPUp0GwCGh1FAfbS0YIzMIGhMCgdBsT%2BpDOA%2BTolMjoEFOQIj1Gj8KVepj3g0qnsSVp6REw440kn9AjPrSji9SKZgCnR8SN3eIAsQ80Yrm8ybvHpp3xNT1J8zFUUbfkGedR%2BiC92Ga1nnUbuvlhZ0uMnmcoEdOfeEMIqqiSKaTXWWILeiQPl5d7vCitWFsjDUI4wMku4RqssL0tAXEyBbE9aTscYvAE031BRvIgPxyMqP16c493AxBoU5BZgK%2FME62naWLO2c7SsPr%2BzfemQYZp9slUHa51ShJlk9MoIoXLJe%2F%2BnJUkwA%3D%3D HTTPSConnectionPool(host='storage.googleapis.com', port=443): Max retries exceeded with url: /wandb-production.appspot.com/zhang-long/YOLOv8/1j1aaaj0/config.yaml?Expires=1707844957&GoogleAccessId=gorilla-files-url-signer-man%40wandb-production.iam.gserviceaccount.com&Signature=ovc2ER9z3SR8biOK8sTfddSwfWBFIGW6fvPUp0GwCGh1FAfbS0YIzMIGhMCgdBsT%2BpDOA%2BTolMjoEFOQIj1Gj8KVepj3g0qnsSVp6REw440kn9AjPrSji9SKZgCnR8SN3eIAsQ80Yrm8ybvHpp3xNT1J8zFUUbfkGedR%2BiC92Ga1nnUbuvlhZ0uMnmcoEdOfeEMIqqiSKaTXWWILeiQPl5d7vCitWFsjDUI4wMku4RqssL0tAXEyBbE9aTscYvAE031BRvIgPxyMqP16c493AxBoU5BZgK%2FME62naWLO2c7SsPr%2BzfemQYZp9slUHa51ShJlk9MoIoXLJe%2F%2BnJUkwA%3D%3D (Caused by NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x0000014CF5586BE0>: Failed to resolve 'storage.googleapis.com' ([Errno 11004] getaddrinfo failed)"))
2024-02-13 01:22:37,656 ERROR   Thread-18 :10788 [internal_api.py:upload_file():1574] upload_file exception https://storage.googleapis.com/wandb-production.appspot.com/zhang-long/YOLOv8/1j1aaaj0/requirements.txt?Expires=1707844957&GoogleAccessId=gorilla-files-url-signer-man%40wandb-production.iam.gserviceaccount.com&Signature=TSpF34YmTuo0e1eeIr63gFlBnIojIK30PBEAle9y5i8HmgaBigOTApX3KZBoX2YVatFrqQi%2Foo6BmuuVxjT%2F%2BmFTyU%2FIcRVgxDNIbxoiQ1cC%2BX9vCCnqlymFcjqJND3ujhg6FRa1V5rDYQiWGdOJ1AHfp%2Bw7aIphbu8nuR1IXZbNRreFE%2FBE6hAolKSDlrIUiSASyZkqi5A8e3czC3qiv1%2BHSW55mNjgiamV%2FVVBNUDIaXNZUmcR9bI2498mfPZLIOzMQqPV6zvXvSwqFTelEdMU%2FDRny3RAhxaqWe%2BmIcmrTkIv6jQNs6q5%2FMGzGkFyFVi1NPvj3KMTT8qbi5w8AA%3D%3D HTTPSConnectionPool(host='storage.googleapis.com', port=443): Max retries exceeded with url: /wandb-production.appspot.com/zhang-long/YOLOv8/1j1aaaj0/requirements.txt?Expires=1707844957&GoogleAccessId=gorilla-files-url-signer-man%40wandb-production.iam.gserviceaccount.com&Signature=TSpF34YmTuo0e1eeIr63gFlBnIojIK30PBEAle9y5i8HmgaBigOTApX3KZBoX2YVatFrqQi%2Foo6BmuuVxjT%2F%2BmFTyU%2FIcRVgxDNIbxoiQ1cC%2BX9vCCnqlymFcjqJND3ujhg6FRa1V5rDYQiWGdOJ1AHfp%2Bw7aIphbu8nuR1IXZbNRreFE%2FBE6hAolKSDlrIUiSASyZkqi5A8e3czC3qiv1%2BHSW55mNjgiamV%2FVVBNUDIaXNZUmcR9bI2498mfPZLIOzMQqPV6zvXvSwqFTelEdMU%2FDRny3RAhxaqWe%2BmIcmrTkIv6jQNs6q5%2FMGzGkFyFVi1NPvj3KMTT8qbi5w8AA%3D%3D (Caused by NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x0000014CF54C65E0>: Failed to resolve 'storage.googleapis.com' ([Errno 11004] getaddrinfo failed)"))
2024-02-13 01:22:37,657 ERROR   Thread-19 :10788 [internal_api.py:upload_file():1574] upload_file exception https://storage.googleapis.com/wandb-production.appspot.com/zhang-long/YOLOv8/1j1aaaj0/wandb-summary.json?Expires=1707844957&GoogleAccessId=gorilla-files-url-signer-man%40wandb-production.iam.gserviceaccount.com&Signature=UzRWOzobii5FHyvyw3E96pzQ1zq88e%2BCUiFtWoCOXXyIpeqV0vYngkwLlTJ6ZSIZUoZ2zNTIyzN376ESJ6UBFjzeXKFR1MNfByN3O95itgoXewIflTfY7gSAGRx3GSc3jRIJHh4KEOdp6vRrsQYR0Ro4pZjyLqNOl94ZNczNSQauISTWJmjukgkG6PJf3Hcq8tuYB%2BLb6uHgG6n78fq0uh6srzIqUL0WvctE8bZ7dtIdAcmf2IvE%2FRZAHnY8DrI2kVF1vwSU2vQbZwtLO7h7ShheG3djUGyl0X8WmzxWXz46c7v19WDAzh58do3RB3GNWkStSnlMZDTfdXr5T4A8Dw%3D%3D HTTPSConnectionPool(host='storage.googleapis.com', port=443): Max retries exceeded with url: /wandb-production.appspot.com/zhang-long/YOLOv8/1j1aaaj0/wandb-summary.json?Expires=1707844957&GoogleAccessId=gorilla-files-url-signer-man%40wandb-production.iam.gserviceaccount.com&Signature=UzRWOzobii5FHyvyw3E96pzQ1zq88e%2BCUiFtWoCOXXyIpeqV0vYngkwLlTJ6ZSIZUoZ2zNTIyzN376ESJ6UBFjzeXKFR1MNfByN3O95itgoXewIflTfY7gSAGRx3GSc3jRIJHh4KEOdp6vRrsQYR0Ro4pZjyLqNOl94ZNczNSQauISTWJmjukgkG6PJf3Hcq8tuYB%2BLb6uHgG6n78fq0uh6srzIqUL0WvctE8bZ7dtIdAcmf2IvE%2FRZAHnY8DrI2kVF1vwSU2vQbZwtLO7h7ShheG3djUGyl0X8WmzxWXz46c7v19WDAzh58do3RB3GNWkStSnlMZDTfdXr5T4A8Dw%3D%3D (Caused by NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x0000014CF54C6F70>: Failed to resolve 'storage.googleapis.com' ([Errno 11004] getaddrinfo failed)"))
2024-02-13 01:22:37,660 ERROR   Thread-17 :10788 [internal_api.py:upload_file():1574] upload_file exception https://storage.googleapis.com/wandb-production.appspot.com/zhang-long/YOLOv8/1j1aaaj0/output.log?Expires=1707844957&GoogleAccessId=gorilla-files-url-signer-man%40wandb-production.iam.gserviceaccount.com&Signature=NE0b%2BdVW5%2FXrch1SYdF%2BITVm9fRDRmqyElFuSmJ74CAikDI37ZLNIK8NcemkiqlEKH5cNmKKZ%2F%2BtRQ0pIrTP1Io7RMl%2FAs%2BEubAuJFY1UQblh7%2FvGDfpSmBvgJYreXSQby0r6SkbKEIG5c6h5H82OaZWowPqXQ8iwX9N9wKAHGbZ1Zjogv2iurqnRWgL5x9r8XF8NDCO3r05SXiTiX%2B%2FzDxZeUkYwI7rWI2zICdSHalO85h5coc44ZLWjbZUJV7Sb5SDlaf5QhKmyVrryAP87xh1A3%2FqcyDtuVzoRogRonbj9ryXjOFnzucNCN4qn5%2BKxPwMs%2FfGF0IFJ2N8iucKEQ%3D%3D HTTPSConnectionPool(host='storage.googleapis.com', port=443): Max retries exceeded with url: /wandb-production.appspot.com/zhang-long/YOLOv8/1j1aaaj0/output.log?Expires=1707844957&GoogleAccessId=gorilla-files-url-signer-man%40wandb-production.iam.gserviceaccount.com&Signature=NE0b%2BdVW5%2FXrch1SYdF%2BITVm9fRDRmqyElFuSmJ74CAikDI37ZLNIK8NcemkiqlEKH5cNmKKZ%2F%2BtRQ0pIrTP1Io7RMl%2FAs%2BEubAuJFY1UQblh7%2FvGDfpSmBvgJYreXSQby0r6SkbKEIG5c6h5H82OaZWowPqXQ8iwX9N9wKAHGbZ1Zjogv2iurqnRWgL5x9r8XF8NDCO3r05SXiTiX%2B%2FzDxZeUkYwI7rWI2zICdSHalO85h5coc44ZLWjbZUJV7Sb5SDlaf5QhKmyVrryAP87xh1A3%2FqcyDtuVzoRogRonbj9ryXjOFnzucNCN4qn5%2BKxPwMs%2FfGF0IFJ2N8iucKEQ%3D%3D (Caused by NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x0000014CF54C6AC0>: Failed to resolve 'storage.googleapis.com' ([Errno 11004] getaddrinfo failed)"))
2024-02-13 01:22:38,687 ERROR   Thread-19 :10788 [internal_api.py:upload_file():1574] upload_file exception https://storage.googleapis.com/wandb-production.appspot.com/zhang-long/YOLOv8/1j1aaaj0/wandb-summary.json?Expires=1707844957&GoogleAccessId=gorilla-files-url-signer-man%40wandb-production.iam.gserviceaccount.com&Signature=UzRWOzobii5FHyvyw3E96pzQ1zq88e%2BCUiFtWoCOXXyIpeqV0vYngkwLlTJ6ZSIZUoZ2zNTIyzN376ESJ6UBFjzeXKFR1MNfByN3O95itgoXewIflTfY7gSAGRx3GSc3jRIJHh4KEOdp6vRrsQYR0Ro4pZjyLqNOl94ZNczNSQauISTWJmjukgkG6PJf3Hcq8tuYB%2BLb6uHgG6n78fq0uh6srzIqUL0WvctE8bZ7dtIdAcmf2IvE%2FRZAHnY8DrI2kVF1vwSU2vQbZwtLO7h7ShheG3djUGyl0X8WmzxWXz46c7v19WDAzh58do3RB3GNWkStSnlMZDTfdXr5T4A8Dw%3D%3D HTTPSConnectionPool(host='storage.googleapis.com', port=443): Max retries exceeded with url: /wandb-production.appspot.com/zhang-long/YOLOv8/1j1aaaj0/wandb-summary.json?Expires=1707844957&GoogleAccessId=gorilla-files-url-signer-man%40wandb-production.iam.gserviceaccount.com&Signature=UzRWOzobii5FHyvyw3E96pzQ1zq88e%2BCUiFtWoCOXXyIpeqV0vYngkwLlTJ6ZSIZUoZ2zNTIyzN376ESJ6UBFjzeXKFR1MNfByN3O95itgoXewIflTfY7gSAGRx3GSc3jRIJHh4KEOdp6vRrsQYR0Ro4pZjyLqNOl94ZNczNSQauISTWJmjukgkG6PJf3Hcq8tuYB%2BLb6uHgG6n78fq0uh6srzIqUL0WvctE8bZ7dtIdAcmf2IvE%2FRZAHnY8DrI2kVF1vwSU2vQbZwtLO7h7ShheG3djUGyl0X8WmzxWXz46c7v19WDAzh58do3RB3GNWkStSnlMZDTfdXr5T4A8Dw%3D%3D (Caused by NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x0000014CF5586C70>: Failed to resolve 'storage.googleapis.com' ([Errno 11004] getaddrinfo failed)"))
2024-02-13 01:22:38,687 ERROR   Thread-18 :10788 [internal_api.py:upload_file():1574] upload_file exception https://storage.googleapis.com/wandb-production.appspot.com/zhang-long/YOLOv8/1j1aaaj0/requirements.txt?Expires=1707844957&GoogleAccessId=gorilla-files-url-signer-man%40wandb-production.iam.gserviceaccount.com&Signature=TSpF34YmTuo0e1eeIr63gFlBnIojIK30PBEAle9y5i8HmgaBigOTApX3KZBoX2YVatFrqQi%2Foo6BmuuVxjT%2F%2BmFTyU%2FIcRVgxDNIbxoiQ1cC%2BX9vCCnqlymFcjqJND3ujhg6FRa1V5rDYQiWGdOJ1AHfp%2Bw7aIphbu8nuR1IXZbNRreFE%2FBE6hAolKSDlrIUiSASyZkqi5A8e3czC3qiv1%2BHSW55mNjgiamV%2FVVBNUDIaXNZUmcR9bI2498mfPZLIOzMQqPV6zvXvSwqFTelEdMU%2FDRny3RAhxaqWe%2BmIcmrTkIv6jQNs6q5%2FMGzGkFyFVi1NPvj3KMTT8qbi5w8AA%3D%3D HTTPSConnectionPool(host='storage.googleapis.com', port=443): Max retries exceeded with url: /wandb-production.appspot.com/zhang-long/YOLOv8/1j1aaaj0/requirements.txt?Expires=1707844957&GoogleAccessId=gorilla-files-url-signer-man%40wandb-production.iam.gserviceaccount.com&Signature=TSpF34YmTuo0e1eeIr63gFlBnIojIK30PBEAle9y5i8HmgaBigOTApX3KZBoX2YVatFrqQi%2Foo6BmuuVxjT%2F%2BmFTyU%2FIcRVgxDNIbxoiQ1cC%2BX9vCCnqlymFcjqJND3ujhg6FRa1V5rDYQiWGdOJ1AHfp%2Bw7aIphbu8nuR1IXZbNRreFE%2FBE6hAolKSDlrIUiSASyZkqi5A8e3czC3qiv1%2BHSW55mNjgiamV%2FVVBNUDIaXNZUmcR9bI2498mfPZLIOzMQqPV6zvXvSwqFTelEdMU%2FDRny3RAhxaqWe%2BmIcmrTkIv6jQNs6q5%2FMGzGkFyFVi1NPvj3KMTT8qbi5w8AA%3D%3D (Caused by NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x0000014CF5586F10>: Failed to resolve 'storage.googleapis.com' ([Errno 11004] getaddrinfo failed)"))
2024-02-13 01:22:38,688 ERROR   Thread-19 :10788 [retry.py:__call__():126] Retry attempt failed:
Traceback (most recent call last):
  File "D:\anaconda\lib\site-packages\urllib3\connection.py", line 203, in _new_conn
    sock = connection.create_connection(
  File "D:\anaconda\lib\site-packages\urllib3\util\connection.py", line 60, in create_connection
    for res in socket.getaddrinfo(host, port, family, socket.SOCK_STREAM):
  File "D:\anaconda\lib\socket.py", line 918, in getaddrinfo
    for res in _socket.getaddrinfo(host, port, family, type, proto, flags):
socket.gaierror: [Errno 11004] getaddrinfo failed

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "D:\anaconda\lib\site-packages\urllib3\connectionpool.py", line 790, in urlopen
    response = self._make_request(
  File "D:\anaconda\lib\site-packages\urllib3\connectionpool.py", line 491, in _make_request
    raise new_e
  File "D:\anaconda\lib\site-packages\urllib3\connectionpool.py", line 467, in _make_request
    self._validate_conn(conn)
  File "D:\anaconda\lib\site-packages\urllib3\connectionpool.py", line 1096, in _validate_conn
    conn.connect()
  File "D:\anaconda\lib\site-packages\urllib3\connection.py", line 611, in connect
    self.sock = sock = self._new_conn()
  File "D:\anaconda\lib\site-packages\urllib3\connection.py", line 210, in _new_conn
    raise NameResolutionError(self.host, self, e) from e
urllib3.exceptions.NameResolutionError: <urllib3.connection.HTTPSConnection object at 0x0000014CF5586C70>: Failed to resolve 'storage.googleapis.com' ([Errno 11004] getaddrinfo failed)

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "D:\anaconda\lib\site-packages\requests\adapters.py", line 486, in send
    resp = conn.urlopen(
  File "D:\anaconda\lib\site-packages\urllib3\connectionpool.py", line 844, in urlopen
    retries = retries.increment(
  File "D:\anaconda\lib\site-packages\urllib3\util\retry.py", line 515, in increment
    raise MaxRetryError(_pool, url, reason) from reason  # type: ignore[arg-type]
urllib3.exceptions.MaxRetryError: HTTPSConnectionPool(host='storage.googleapis.com', port=443): Max retries exceeded with url: /wandb-production.appspot.com/zhang-long/YOLOv8/1j1aaaj0/wandb-summary.json?Expires=1707844957&GoogleAccessId=gorilla-files-url-signer-man%40wandb-production.iam.gserviceaccount.com&Signature=UzRWOzobii5FHyvyw3E96pzQ1zq88e%2BCUiFtWoCOXXyIpeqV0vYngkwLlTJ6ZSIZUoZ2zNTIyzN376ESJ6UBFjzeXKFR1MNfByN3O95itgoXewIflTfY7gSAGRx3GSc3jRIJHh4KEOdp6vRrsQYR0Ro4pZjyLqNOl94ZNczNSQauISTWJmjukgkG6PJf3Hcq8tuYB%2BLb6uHgG6n78fq0uh6srzIqUL0WvctE8bZ7dtIdAcmf2IvE%2FRZAHnY8DrI2kVF1vwSU2vQbZwtLO7h7ShheG3djUGyl0X8WmzxWXz46c7v19WDAzh58do3RB3GNWkStSnlMZDTfdXr5T4A8Dw%3D%3D (Caused by NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x0000014CF5586C70>: Failed to resolve 'storage.googleapis.com' ([Errno 11004] getaddrinfo failed)"))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "D:\anaconda\lib\site-packages\wandb\sdk\internal\internal_api.py", line 1571, in upload_file
    response = requests.put(url, data=progress, headers=extra_headers)
  File "D:\anaconda\lib\site-packages\requests\api.py", line 130, in put
    return request("put", url, data=data, **kwargs)
  File "D:\anaconda\lib\site-packages\requests\api.py", line 59, in request
    return session.request(method=method, url=url, **kwargs)
  File "D:\anaconda\lib\site-packages\requests\sessions.py", line 589, in request
    resp = self.send(prep, **send_kwargs)
  File "D:\anaconda\lib\site-packages\requests\sessions.py", line 703, in send
    r = adapter.send(request, **kwargs)
  File "D:\anaconda\lib\site-packages\requests\adapters.py", line 519, in send
    raise ConnectionError(e, request=request)
requests.exceptions.ConnectionError: HTTPSConnectionPool(host='storage.googleapis.com', port=443): Max retries exceeded with url: /wandb-production.appspot.com/zhang-long/YOLOv8/1j1aaaj0/wandb-summary.json?Expires=1707844957&GoogleAccessId=gorilla-files-url-signer-man%40wandb-production.iam.gserviceaccount.com&Signature=UzRWOzobii5FHyvyw3E96pzQ1zq88e%2BCUiFtWoCOXXyIpeqV0vYngkwLlTJ6ZSIZUoZ2zNTIyzN376ESJ6UBFjzeXKFR1MNfByN3O95itgoXewIflTfY7gSAGRx3GSc3jRIJHh4KEOdp6vRrsQYR0Ro4pZjyLqNOl94ZNczNSQauISTWJmjukgkG6PJf3Hcq8tuYB%2BLb6uHgG6n78fq0uh6srzIqUL0WvctE8bZ7dtIdAcmf2IvE%2FRZAHnY8DrI2kVF1vwSU2vQbZwtLO7h7ShheG3djUGyl0X8WmzxWXz46c7v19WDAzh58do3RB3GNWkStSnlMZDTfdXr5T4A8Dw%3D%3D (Caused by NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x0000014CF5586C70>: Failed to resolve 'storage.googleapis.com' ([Errno 11004] getaddrinfo failed)"))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "D:\anaconda\lib\site-packages\wandb\sdk\lib\retry.py", line 102, in __call__
    result = self._call_fn(*args, **kwargs)
  File "D:\anaconda\lib\site-packages\wandb\sdk\internal\internal_api.py", line 1583, in upload_file
    six.reraise(type(e), e, sys.exc_info()[2])
  File "D:\anaconda\lib\site-packages\six.py", line 718, in reraise
    raise value.with_traceback(tb)
  File "D:\anaconda\lib\site-packages\wandb\sdk\internal\internal_api.py", line 1571, in upload_file
    response = requests.put(url, data=progress, headers=extra_headers)
  File "D:\anaconda\lib\site-packages\requests\api.py", line 130, in put
    return request("put", url, data=data, **kwargs)
  File "D:\anaconda\lib\site-packages\requests\api.py", line 59, in request
    return session.request(method=method, url=url, **kwargs)
  File "D:\anaconda\lib\site-packages\requests\sessions.py", line 589, in request
    resp = self.send(prep, **send_kwargs)
  File "D:\anaconda\lib\site-packages\requests\sessions.py", line 703, in send
    r = adapter.send(request, **kwargs)
  File "D:\anaconda\lib\site-packages\requests\adapters.py", line 519, in send
    raise ConnectionError(e, request=request)
wandb.sdk.lib.retry.TransientError: None
2024-02-13 01:22:38,688 ERROR   Thread-18 :10788 [retry.py:__call__():126] Retry attempt failed:
Traceback (most recent call last):
  File "D:\anaconda\lib\site-packages\urllib3\connection.py", line 203, in _new_conn
    sock = connection.create_connection(
  File "D:\anaconda\lib\site-packages\urllib3\util\connection.py", line 60, in create_connection
    for res in socket.getaddrinfo(host, port, family, socket.SOCK_STREAM):
  File "D:\anaconda\lib\socket.py", line 918, in getaddrinfo
    for res in _socket.getaddrinfo(host, port, family, type, proto, flags):
socket.gaierror: [Errno 11004] getaddrinfo failed

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "D:\anaconda\lib\site-packages\urllib3\connectionpool.py", line 790, in urlopen
    response = self._make_request(
  File "D:\anaconda\lib\site-packages\urllib3\connectionpool.py", line 491, in _make_request
    raise new_e
  File "D:\anaconda\lib\site-packages\urllib3\connectionpool.py", line 467, in _make_request
    self._validate_conn(conn)
  File "D:\anaconda\lib\site-packages\urllib3\connectionpool.py", line 1096, in _validate_conn
    conn.connect()
  File "D:\anaconda\lib\site-packages\urllib3\connection.py", line 611, in connect
    self.sock = sock = self._new_conn()
  File "D:\anaconda\lib\site-packages\urllib3\connection.py", line 210, in _new_conn
    raise NameResolutionError(self.host, self, e) from e
urllib3.exceptions.NameResolutionError: <urllib3.connection.HTTPSConnection object at 0x0000014CF5586F10>: Failed to resolve 'storage.googleapis.com' ([Errno 11004] getaddrinfo failed)

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "D:\anaconda\lib\site-packages\requests\adapters.py", line 486, in send
    resp = conn.urlopen(
  File "D:\anaconda\lib\site-packages\urllib3\connectionpool.py", line 844, in urlopen
    retries = retries.increment(
  File "D:\anaconda\lib\site-packages\urllib3\util\retry.py", line 515, in increment
    raise MaxRetryError(_pool, url, reason) from reason  # type: ignore[arg-type]
urllib3.exceptions.MaxRetryError: HTTPSConnectionPool(host='storage.googleapis.com', port=443): Max retries exceeded with url: /wandb-production.appspot.com/zhang-long/YOLOv8/1j1aaaj0/requirements.txt?Expires=1707844957&GoogleAccessId=gorilla-files-url-signer-man%40wandb-production.iam.gserviceaccount.com&Signature=TSpF34YmTuo0e1eeIr63gFlBnIojIK30PBEAle9y5i8HmgaBigOTApX3KZBoX2YVatFrqQi%2Foo6BmuuVxjT%2F%2BmFTyU%2FIcRVgxDNIbxoiQ1cC%2BX9vCCnqlymFcjqJND3ujhg6FRa1V5rDYQiWGdOJ1AHfp%2Bw7aIphbu8nuR1IXZbNRreFE%2FBE6hAolKSDlrIUiSASyZkqi5A8e3czC3qiv1%2BHSW55mNjgiamV%2FVVBNUDIaXNZUmcR9bI2498mfPZLIOzMQqPV6zvXvSwqFTelEdMU%2FDRny3RAhxaqWe%2BmIcmrTkIv6jQNs6q5%2FMGzGkFyFVi1NPvj3KMTT8qbi5w8AA%3D%3D (Caused by NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x0000014CF5586F10>: Failed to resolve 'storage.googleapis.com' ([Errno 11004] getaddrinfo failed)"))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "D:\anaconda\lib\site-packages\wandb\sdk\internal\internal_api.py", line 1571, in upload_file
    response = requests.put(url, data=progress, headers=extra_headers)
  File "D:\anaconda\lib\site-packages\requests\api.py", line 130, in put
    return request("put", url, data=data, **kwargs)
  File "D:\anaconda\lib\site-packages\requests\api.py", line 59, in request
    return session.request(method=method, url=url, **kwargs)
  File "D:\anaconda\lib\site-packages\requests\sessions.py", line 589, in request
    resp = self.send(prep, **send_kwargs)
  File "D:\anaconda\lib\site-packages\requests\sessions.py", line 703, in send
    r = adapter.send(request, **kwargs)
  File "D:\anaconda\lib\site-packages\requests\adapters.py", line 519, in send
    raise ConnectionError(e, request=request)
requests.exceptions.ConnectionError: HTTPSConnectionPool(host='storage.googleapis.com', port=443): Max retries exceeded with url: /wandb-production.appspot.com/zhang-long/YOLOv8/1j1aaaj0/requirements.txt?Expires=1707844957&GoogleAccessId=gorilla-files-url-signer-man%40wandb-production.iam.gserviceaccount.com&Signature=TSpF34YmTuo0e1eeIr63gFlBnIojIK30PBEAle9y5i8HmgaBigOTApX3KZBoX2YVatFrqQi%2Foo6BmuuVxjT%2F%2BmFTyU%2FIcRVgxDNIbxoiQ1cC%2BX9vCCnqlymFcjqJND3ujhg6FRa1V5rDYQiWGdOJ1AHfp%2Bw7aIphbu8nuR1IXZbNRreFE%2FBE6hAolKSDlrIUiSASyZkqi5A8e3czC3qiv1%2BHSW55mNjgiamV%2FVVBNUDIaXNZUmcR9bI2498mfPZLIOzMQqPV6zvXvSwqFTelEdMU%2FDRny3RAhxaqWe%2BmIcmrTkIv6jQNs6q5%2FMGzGkFyFVi1NPvj3KMTT8qbi5w8AA%3D%3D (Caused by NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x0000014CF5586F10>: Failed to resolve 'storage.googleapis.com' ([Errno 11004] getaddrinfo failed)"))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "D:\anaconda\lib\site-packages\wandb\sdk\lib\retry.py", line 102, in __call__
    result = self._call_fn(*args, **kwargs)
  File "D:\anaconda\lib\site-packages\wandb\sdk\internal\internal_api.py", line 1583, in upload_file
    six.reraise(type(e), e, sys.exc_info()[2])
  File "D:\anaconda\lib\site-packages\six.py", line 718, in reraise
    raise value.with_traceback(tb)
  File "D:\anaconda\lib\site-packages\wandb\sdk\internal\internal_api.py", line 1571, in upload_file
    response = requests.put(url, data=progress, headers=extra_headers)
  File "D:\anaconda\lib\site-packages\requests\api.py", line 130, in put
    return request("put", url, data=data, **kwargs)
  File "D:\anaconda\lib\site-packages\requests\api.py", line 59, in request
    return session.request(method=method, url=url, **kwargs)
  File "D:\anaconda\lib\site-packages\requests\sessions.py", line 589, in request
    resp = self.send(prep, **send_kwargs)
  File "D:\anaconda\lib\site-packages\requests\sessions.py", line 703, in send
    r = adapter.send(request, **kwargs)
  File "D:\anaconda\lib\site-packages\requests\adapters.py", line 519, in send
    raise ConnectionError(e, request=request)
wandb.sdk.lib.retry.TransientError: None
2024-02-13 01:22:38,725 ERROR   Thread-16 :10788 [internal_api.py:upload_file():1574] upload_file exception https://storage.googleapis.com/wandb-production.appspot.com/zhang-long/YOLOv8/1j1aaaj0/config.yaml?Expires=1707844957&GoogleAccessId=gorilla-files-url-signer-man%40wandb-production.iam.gserviceaccount.com&Signature=ovc2ER9z3SR8biOK8sTfddSwfWBFIGW6fvPUp0GwCGh1FAfbS0YIzMIGhMCgdBsT%2BpDOA%2BTolMjoEFOQIj1Gj8KVepj3g0qnsSVp6REw440kn9AjPrSji9SKZgCnR8SN3eIAsQ80Yrm8ybvHpp3xNT1J8zFUUbfkGedR%2BiC92Ga1nnUbuvlhZ0uMnmcoEdOfeEMIqqiSKaTXWWILeiQPl5d7vCitWFsjDUI4wMku4RqssL0tAXEyBbE9aTscYvAE031BRvIgPxyMqP16c493AxBoU5BZgK%2FME62naWLO2c7SsPr%2BzfemQYZp9slUHa51ShJlk9MoIoXLJe%2F%2BnJUkwA%3D%3D HTTPSConnectionPool(host='storage.googleapis.com', port=443): Max retries exceeded with url: /wandb-production.appspot.com/zhang-long/YOLOv8/1j1aaaj0/config.yaml?Expires=1707844957&GoogleAccessId=gorilla-files-url-signer-man%40wandb-production.iam.gserviceaccount.com&Signature=ovc2ER9z3SR8biOK8sTfddSwfWBFIGW6fvPUp0GwCGh1FAfbS0YIzMIGhMCgdBsT%2BpDOA%2BTolMjoEFOQIj1Gj8KVepj3g0qnsSVp6REw440kn9AjPrSji9SKZgCnR8SN3eIAsQ80Yrm8ybvHpp3xNT1J8zFUUbfkGedR%2BiC92Ga1nnUbuvlhZ0uMnmcoEdOfeEMIqqiSKaTXWWILeiQPl5d7vCitWFsjDUI4wMku4RqssL0tAXEyBbE9aTscYvAE031BRvIgPxyMqP16c493AxBoU5BZgK%2FME62naWLO2c7SsPr%2BzfemQYZp9slUHa51ShJlk9MoIoXLJe%2F%2BnJUkwA%3D%3D (Caused by NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x0000014CF54C6D30>: Failed to resolve 'storage.googleapis.com' ([Errno 11004] getaddrinfo failed)"))
2024-02-13 01:22:38,853 ERROR   Thread-17 :10788 [internal_api.py:upload_file():1574] upload_file exception https://storage.googleapis.com/wandb-production.appspot.com/zhang-long/YOLOv8/1j1aaaj0/output.log?Expires=1707844957&GoogleAccessId=gorilla-files-url-signer-man%40wandb-production.iam.gserviceaccount.com&Signature=NE0b%2BdVW5%2FXrch1SYdF%2BITVm9fRDRmqyElFuSmJ74CAikDI37ZLNIK8NcemkiqlEKH5cNmKKZ%2F%2BtRQ0pIrTP1Io7RMl%2FAs%2BEubAuJFY1UQblh7%2FvGDfpSmBvgJYreXSQby0r6SkbKEIG5c6h5H82OaZWowPqXQ8iwX9N9wKAHGbZ1Zjogv2iurqnRWgL5x9r8XF8NDCO3r05SXiTiX%2B%2FzDxZeUkYwI7rWI2zICdSHalO85h5coc44ZLWjbZUJV7Sb5SDlaf5QhKmyVrryAP87xh1A3%2FqcyDtuVzoRogRonbj9ryXjOFnzucNCN4qn5%2BKxPwMs%2FfGF0IFJ2N8iucKEQ%3D%3D HTTPSConnectionPool(host='storage.googleapis.com', port=443): Max retries exceeded with url: /wandb-production.appspot.com/zhang-long/YOLOv8/1j1aaaj0/output.log?Expires=1707844957&GoogleAccessId=gorilla-files-url-signer-man%40wandb-production.iam.gserviceaccount.com&Signature=NE0b%2BdVW5%2FXrch1SYdF%2BITVm9fRDRmqyElFuSmJ74CAikDI37ZLNIK8NcemkiqlEKH5cNmKKZ%2F%2BtRQ0pIrTP1Io7RMl%2FAs%2BEubAuJFY1UQblh7%2FvGDfpSmBvgJYreXSQby0r6SkbKEIG5c6h5H82OaZWowPqXQ8iwX9N9wKAHGbZ1Zjogv2iurqnRWgL5x9r8XF8NDCO3r05SXiTiX%2B%2FzDxZeUkYwI7rWI2zICdSHalO85h5coc44ZLWjbZUJV7Sb5SDlaf5QhKmyVrryAP87xh1A3%2FqcyDtuVzoRogRonbj9ryXjOFnzucNCN4qn5%2BKxPwMs%2FfGF0IFJ2N8iucKEQ%3D%3D (Caused by NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x0000014CF54BD340>: Failed to resolve 'storage.googleapis.com' ([Errno 11004] getaddrinfo failed)"))
2024-02-13 01:22:40,787 ERROR   Thread-19 :10788 [internal_api.py:upload_file():1574] upload_file exception https://storage.googleapis.com/wandb-production.appspot.com/zhang-long/YOLOv8/1j1aaaj0/wandb-summary.json?Expires=1707844957&GoogleAccessId=gorilla-files-url-signer-man%40wandb-production.iam.gserviceaccount.com&Signature=UzRWOzobii5FHyvyw3E96pzQ1zq88e%2BCUiFtWoCOXXyIpeqV0vYngkwLlTJ6ZSIZUoZ2zNTIyzN376ESJ6UBFjzeXKFR1MNfByN3O95itgoXewIflTfY7gSAGRx3GSc3jRIJHh4KEOdp6vRrsQYR0Ro4pZjyLqNOl94ZNczNSQauISTWJmjukgkG6PJf3Hcq8tuYB%2BLb6uHgG6n78fq0uh6srzIqUL0WvctE8bZ7dtIdAcmf2IvE%2FRZAHnY8DrI2kVF1vwSU2vQbZwtLO7h7ShheG3djUGyl0X8WmzxWXz46c7v19WDAzh58do3RB3GNWkStSnlMZDTfdXr5T4A8Dw%3D%3D HTTPSConnectionPool(host='storage.googleapis.com', port=443): Max retries exceeded with url: /wandb-production.appspot.com/zhang-long/YOLOv8/1j1aaaj0/wandb-summary.json?Expires=1707844957&GoogleAccessId=gorilla-files-url-signer-man%40wandb-production.iam.gserviceaccount.com&Signature=UzRWOzobii5FHyvyw3E96pzQ1zq88e%2BCUiFtWoCOXXyIpeqV0vYngkwLlTJ6ZSIZUoZ2zNTIyzN376ESJ6UBFjzeXKFR1MNfByN3O95itgoXewIflTfY7gSAGRx3GSc3jRIJHh4KEOdp6vRrsQYR0Ro4pZjyLqNOl94ZNczNSQauISTWJmjukgkG6PJf3Hcq8tuYB%2BLb6uHgG6n78fq0uh6srzIqUL0WvctE8bZ7dtIdAcmf2IvE%2FRZAHnY8DrI2kVF1vwSU2vQbZwtLO7h7ShheG3djUGyl0X8WmzxWXz46c7v19WDAzh58do3RB3GNWkStSnlMZDTfdXr5T4A8Dw%3D%3D (Caused by NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x0000014CEBBAEC10>: Failed to resolve 'storage.googleapis.com' ([Errno 11004] getaddrinfo failed)"))
2024-02-13 01:22:41,000 ERROR   Thread-16 :10788 [internal_api.py:upload_file():1574] upload_file exception https://storage.googleapis.com/wandb-production.appspot.com/zhang-long/YOLOv8/1j1aaaj0/config.yaml?Expires=1707844957&GoogleAccessId=gorilla-files-url-signer-man%40wandb-production.iam.gserviceaccount.com&Signature=ovc2ER9z3SR8biOK8sTfddSwfWBFIGW6fvPUp0GwCGh1FAfbS0YIzMIGhMCgdBsT%2BpDOA%2BTolMjoEFOQIj1Gj8KVepj3g0qnsSVp6REw440kn9AjPrSji9SKZgCnR8SN3eIAsQ80Yrm8ybvHpp3xNT1J8zFUUbfkGedR%2BiC92Ga1nnUbuvlhZ0uMnmcoEdOfeEMIqqiSKaTXWWILeiQPl5d7vCitWFsjDUI4wMku4RqssL0tAXEyBbE9aTscYvAE031BRvIgPxyMqP16c493AxBoU5BZgK%2FME62naWLO2c7SsPr%2BzfemQYZp9slUHa51ShJlk9MoIoXLJe%2F%2BnJUkwA%3D%3D HTTPSConnectionPool(host='storage.googleapis.com', port=443): Max retries exceeded with url: /wandb-production.appspot.com/zhang-long/YOLOv8/1j1aaaj0/config.yaml?Expires=1707844957&GoogleAccessId=gorilla-files-url-signer-man%40wandb-production.iam.gserviceaccount.com&Signature=ovc2ER9z3SR8biOK8sTfddSwfWBFIGW6fvPUp0GwCGh1FAfbS0YIzMIGhMCgdBsT%2BpDOA%2BTolMjoEFOQIj1Gj8KVepj3g0qnsSVp6REw440kn9AjPrSji9SKZgCnR8SN3eIAsQ80Yrm8ybvHpp3xNT1J8zFUUbfkGedR%2BiC92Ga1nnUbuvlhZ0uMnmcoEdOfeEMIqqiSKaTXWWILeiQPl5d7vCitWFsjDUI4wMku4RqssL0tAXEyBbE9aTscYvAE031BRvIgPxyMqP16c493AxBoU5BZgK%2FME62naWLO2c7SsPr%2BzfemQYZp9slUHa51ShJlk9MoIoXLJe%2F%2BnJUkwA%3D%3D (Caused by NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x0000014CF5586FD0>: Failed to resolve 'storage.googleapis.com' ([Errno 11004] getaddrinfo failed)"))
2024-02-13 01:22:41,015 ERROR   Thread-17 :10788 [internal_api.py:upload_file():1574] upload_file exception https://storage.googleapis.com/wandb-production.appspot.com/zhang-long/YOLOv8/1j1aaaj0/output.log?Expires=1707844957&GoogleAccessId=gorilla-files-url-signer-man%40wandb-production.iam.gserviceaccount.com&Signature=NE0b%2BdVW5%2FXrch1SYdF%2BITVm9fRDRmqyElFuSmJ74CAikDI37ZLNIK8NcemkiqlEKH5cNmKKZ%2F%2BtRQ0pIrTP1Io7RMl%2FAs%2BEubAuJFY1UQblh7%2FvGDfpSmBvgJYreXSQby0r6SkbKEIG5c6h5H82OaZWowPqXQ8iwX9N9wKAHGbZ1Zjogv2iurqnRWgL5x9r8XF8NDCO3r05SXiTiX%2B%2FzDxZeUkYwI7rWI2zICdSHalO85h5coc44ZLWjbZUJV7Sb5SDlaf5QhKmyVrryAP87xh1A3%2FqcyDtuVzoRogRonbj9ryXjOFnzucNCN4qn5%2BKxPwMs%2FfGF0IFJ2N8iucKEQ%3D%3D HTTPSConnectionPool(host='storage.googleapis.com', port=443): Max retries exceeded with url: /wandb-production.appspot.com/zhang-long/YOLOv8/1j1aaaj0/output.log?Expires=1707844957&GoogleAccessId=gorilla-files-url-signer-man%40wandb-production.iam.gserviceaccount.com&Signature=NE0b%2BdVW5%2FXrch1SYdF%2BITVm9fRDRmqyElFuSmJ74CAikDI37ZLNIK8NcemkiqlEKH5cNmKKZ%2F%2BtRQ0pIrTP1Io7RMl%2FAs%2BEubAuJFY1UQblh7%2FvGDfpSmBvgJYreXSQby0r6SkbKEIG5c6h5H82OaZWowPqXQ8iwX9N9wKAHGbZ1Zjogv2iurqnRWgL5x9r8XF8NDCO3r05SXiTiX%2B%2FzDxZeUkYwI7rWI2zICdSHalO85h5coc44ZLWjbZUJV7Sb5SDlaf5QhKmyVrryAP87xh1A3%2FqcyDtuVzoRogRonbj9ryXjOFnzucNCN4qn5%2BKxPwMs%2FfGF0IFJ2N8iucKEQ%3D%3D (Caused by NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x0000014CF5591F70>: Failed to resolve 'storage.googleapis.com' ([Errno 11004] getaddrinfo failed)"))
2024-02-13 01:22:41,166 ERROR   Thread-18 :10788 [internal_api.py:upload_file():1574] upload_file exception https://storage.googleapis.com/wandb-production.appspot.com/zhang-long/YOLOv8/1j1aaaj0/requirements.txt?Expires=1707844957&GoogleAccessId=gorilla-files-url-signer-man%40wandb-production.iam.gserviceaccount.com&Signature=TSpF34YmTuo0e1eeIr63gFlBnIojIK30PBEAle9y5i8HmgaBigOTApX3KZBoX2YVatFrqQi%2Foo6BmuuVxjT%2F%2BmFTyU%2FIcRVgxDNIbxoiQ1cC%2BX9vCCnqlymFcjqJND3ujhg6FRa1V5rDYQiWGdOJ1AHfp%2Bw7aIphbu8nuR1IXZbNRreFE%2FBE6hAolKSDlrIUiSASyZkqi5A8e3czC3qiv1%2BHSW55mNjgiamV%2FVVBNUDIaXNZUmcR9bI2498mfPZLIOzMQqPV6zvXvSwqFTelEdMU%2FDRny3RAhxaqWe%2BmIcmrTkIv6jQNs6q5%2FMGzGkFyFVi1NPvj3KMTT8qbi5w8AA%3D%3D HTTPSConnectionPool(host='storage.googleapis.com', port=443): Max retries exceeded with url: /wandb-production.appspot.com/zhang-long/YOLOv8/1j1aaaj0/requirements.txt?Expires=1707844957&GoogleAccessId=gorilla-files-url-signer-man%40wandb-production.iam.gserviceaccount.com&Signature=TSpF34YmTuo0e1eeIr63gFlBnIojIK30PBEAle9y5i8HmgaBigOTApX3KZBoX2YVatFrqQi%2Foo6BmuuVxjT%2F%2BmFTyU%2FIcRVgxDNIbxoiQ1cC%2BX9vCCnqlymFcjqJND3ujhg6FRa1V5rDYQiWGdOJ1AHfp%2Bw7aIphbu8nuR1IXZbNRreFE%2FBE6hAolKSDlrIUiSASyZkqi5A8e3czC3qiv1%2BHSW55mNjgiamV%2FVVBNUDIaXNZUmcR9bI2498mfPZLIOzMQqPV6zvXvSwqFTelEdMU%2FDRny3RAhxaqWe%2BmIcmrTkIv6jQNs6q5%2FMGzGkFyFVi1NPvj3KMTT8qbi5w8AA%3D%3D (Caused by NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x0000014CF55941C0>: Failed to resolve 'storage.googleapis.com' ([Errno 11004] getaddrinfo failed)"))
